the-turing-way/the-turing-way

- README.md
text could probably be improved later but hope this will do for the presentation
> Add team photo to readme

- conferences/abstracts/LIBER-submission.md
Adding submission as discussed in #97
> Add LIBER submission

- hopes_and_dreams.md
Adding today's feeback - GitHub specific comments will go in the GitHub collaboration chapter (tbd)
> Add January pizza party feedback

- ISSUE_TEMPLATE.md
As pointed out in #131 - not everyone will be able to add labels so I adjusted the label section to cover that going forward
> Address label assignment

- ways_of_working.md
Ready to merge. @r-j-arnold or @pherterich please could you take a look and merge if happy?
> Add Martin's preferred contact method to ways of working document

- ways_of_working.md
Change reference to gitter meetings on wednesdays to slack in ways of working document
> Change gitter to slack

- ways_of_working.md
SORRY THIS HAS TAKEN SO LONG! 😭
> Add KW preferred contact to ways of working

- chapters/version_control.md
See https://www.dictionary.com/e/practice-vs-practise/.  "Practice" is the noun,
and in British English, "practise" is the verb.  "Practise" is never used as a noun.
> version_control.md: Correct spelling of "practice"

- project_management/dissemination_plan.md
* updated conferences with the various open issues 
* Linked workshop section to the relevant issue
> Conference update to dissemination plan

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
I think we could make better use of the fact that html comments aren't rendered.
This pull request contains a new pull request tempate and includes my suggestions for re-formatting the issue template we have.
This is very much open for discussion! Thank you to everyone who's been using the current template, it really helps nudge folks to add the information we need 🤗
> Update issue and pull request templates

- humans.md
First attempt to include acknowledgments as discussed in #125
- adding the icons to acknowledge contributors
- first attempt at a list of contributors so far
High level feedback if this is reflecting what we discussed. I made an attempt to add icons but will leave it to the individual contributors to pick the ones missing for themselves in further PRs. Same for people I've missed out so far.
> Add contributor acknowledgements to humans.md

- case_studies.md
- tips_and_tricks_survey.md
Kirstie's edits to be merged into #167 if ok'd by @pherterich 
* Changed the name from "case study" to a survey for tips and tricks
* Added description text for all the questions
* Added a couple of questions
* Clarified a few sentences
I hope this doesn't chagne anything too much! Happy to adjust as necessary.
> Kirstie's edits to case study

- project_management/first_newsletter.md
Feedback on #165 
* Just a few phrasing differences. Hopefully very small.
> Kirstie's edits for first newsletter

- project_management/resources.md
Doesn't fix a current issue 
It's just the worlds tiniest typo!
* Fix typo
> [Quick fix] Fix typo

- CONTRIBUTING.md
In the contributing guidelines update description of the process of writing a chapter and add more detail. Most importantly outline that major and minor reviews of new chapters are to be discussed on separate pull requests.
Following this we can close #128.
> Update process of writing chapters

- README.md
Doesn't close an open issue.
* Added badge at the top of the README and link in contact us section to tiny letter subscription page.
> Add link to newsletter in README

- project_management/dissemination_plan.md
Adding Sheffield RSE mailing list
Fixes #<NUM> 
> Add RSE Sheffield mailing list

- .github/PULL_REQUEST_TEMPLATE.md
Doesn't close an open issue.
This is just a tiny stylistic thing that's been bugging me, especially when opening a PR via mobile.
* Merge two comments in the PR issue template into one html comment.
> Format two comments into one in PR issue template

- .all-contributorsrc
- README.md
Reverts alan-turing-institute/the-turing-way#200
> Revert "docs: add pherterich as a contributor"

- chapters/containerization-ots-talk-notes/Makefile
- chapters/containerization-ots-talk-notes/clone-example.c
- chapters/containerization-ots-talk-notes/container.c
- chapters/containerization-ots-talk-notes/containers.org
- chapters/containerization-ots-talk-notes/fork-example.c
Adds some notes for a talk on containerization that could be helpful for a TW chapter on containers
> Add some notes on containerization

- README.md
Doesn't fix an open issue.
I changed the colour of the heart in the badge that links to the newsletter while on the train this morning.
That was a terrible idea, it looks rubbish now, so lets put it back to this red heart and I promise not to fiddle so much from my commute in!
* Fix black boring plain emoji heart back to nice red one
> Change heart emoji again

- CODE_OF_CONDUCT.md
> Updated code of conduct - ready for workshops

- workshops/boost-research-reproducibility-binder/before_workshop.md
Email to participants before the Manchester workshop
Fixes #222 
* Email to participants
* Typos & language
> Workshop comms

- workshops/README.md
Doesn't fix any open issues
This creates a README file that will automatically render when anyone visits the workshops folder and hopefully give them a little overview of what's available there.
* Just a little readme 😸 
> Add readme for workshops folder

- CONTRIBUTING.md
1. Removes the reference to BIDS Starter Kit (copy'n'paste letover I assume) from the contributing guidelines, as it may have confused readers.
2. Format MD formatting examples for *italics* & **bold** to help people see the result of formatting  (same as for link).
> Remove BIDS Starter Kit mention, format bold/italics examples

- book_skeleton.md
The book skeleton has a list of completed/WIP/needed chapters. Some chapter are now done/are now being worked on, so update this list.
Update book skeleton as to which chapters are complete/in progress
Have I made any stupid mistakes?
> [Quick fix] Update book skeleton as to which chapters are complete/in progress

- chapters/open_research.md
Just remove an extraneous `s`.
> Fix Typo in open_research.md

- chapters/reproducibility.md
Just inserted a missing `t` in `deailed`.
> Fix Typo in reproducibility.md

- .github/PULL_REQUEST_TEMPLATE.md
Fixes no open issues
* Fix broken path to humans.md file in PR template
> Fix broken path to humans.md in PR template

- workshops/boost-research-reproducibility-binder/before_workshop.md
Add text for pre-workshop email to attendees for the London Binder workshop
- Typos
- @LouiseABowler could you add the accessing the Turing info please?
> Add London workshop email

- conferences/abstracts/ukoswg_submission.md
Moving submission from issues to our abstract folder.
Closes #230 
> Add UKOSWG submission

- conferences/presentations/UKRI_cloud_2019-02-12/UKRI_cloud_demo_2019-02-12.md
Changing the link for my matplotlib demo repo to the repo in binder-examples. This is so I can use the original repo for the workshops.
* Updated link
> [Quick fix] Update UKRI talk to change matplotlib demo to binder-examples

- conferences/abstracts/CarpentryConnect_submission.md
I've made a start to help with #257 creating a zombie abstract from texts we've produced so far. It will need improving and there is room for 80 more words to do so but should give @KirstieJane a start on a submission.
> Start on CarpentryCon submission

- workshops/boost-research-reproducibility-binder/paired_examples.md
This PR updates the GitHub repo links to the paired examples in `paired_examples.md` to the harmonised versions I have forked. I also mention which tools (e.g. command line, notebooks) each repo uses so attendees know what sort of environment to expect.
* Change GitHub repo links in 'paired_examples.md`
> [Quick fix] Update GitHub links to paired examples

- workshops/build-a-binderhub/agenda.md
Quick fix on the agenda as discussed in the meeting.
> Kw binderhub agenda

- workshops/build-a-binderhub/agenda.md
We updated the binderhub workshop agenda in our meeting on Wednesday.
Lets go ahead and merge it to master 🚀 
> [Quick fix] Merge updated Sheffield workshop agenda to master

- workshops/boost-research-reproducibility-binder/README.md
This README should help people find the files they're looking for rather than hope that they can understand everything from the file names!
* Create README
> Create boost reproducibilty workshop readme file

- workshops/build-a-binderhub/hack-my-binderhub.md
Adding the materials associated with the afternoon Hack my BinderHub session. Because it is more of a practical exercise and much of the information is useful during group work, I opted for an explanatory md format. I also think it will be more useful if repeating the workshop this way.
* Adding `hack-my-binderhub.md` to workshop materials
- [x ] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).
> [Ready for Review] Add hack-my-binderhub session materials

- contributors.md
- project_management/dissemination_plan.md
- project_management/turing-webpage.md
- ways_of_working.md
I added info about Rachael Ainsworth (myself) to relevant pages within the Turing Way repo (social media, contact, bio, etc).
* Updated ways_of_working.md & contributors.md
* Added name/info to project_management/dissemination_plan.md & turing-webpage.md
> Added Rachael Ainsworth info to relevant pages

- communications/newsletters/newsletter_03_Mar2019.md
> Incorporate KW suggestions to newsletter

- chapters/rdm.md
Just making the RDM chapter draft more visible so others can edit on top.
Fixes #179 
First proper draft!!!
* Mainly high level comments, anything more substantial please add those comments to #179 for a next round of editing or someone else to pick up.
I will do some proper linking of the ToC later - it shouldn't be too long to read I hope.
> [Ready for review] RDM chapter

- .travis.yml
- scripts/test-file-size.sh
Fixes #351 
The PR adds CI which runs a bash test script that fails if files larger than 5M are found in the repository. The script also allows adding files paths to files to be ignored during the test, allowing us to include larger files if required.
* *Add `.travis.yml`* configured with `language: minimal` and to run a file checking test script
* *Add `scripts/test-file-size.sh* test script
- should these instructions also be included somewhere else?
@ptooley and @ptheywood also contributed to this PR
> add file size test

- CONTRIBUTING.md
Added some of the suggestions from #16, focusing on the Making a change with a pull request section.
* Fixed some typos/incomplete sentences throughout the file
* Adapted the Making a change with a pull request section of the CONTRIBUTING.md from the [BIDS Starter Kit](https://github.com/bids-standard/bids-starter-kit) (License: CC-BY) to the Turing Way, specifically:
* Note - the answer here is to link to the version control chapter rather than reinvent the wheel.
* Here's a nice blog post: https://nvie.com/posts/a-successful-git-branching-model
* To do that you'll need to syncing branches and forks with upstream: https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser
> edited CONTRIBUTING.md section on Making a change with a pull request

- communications/newsletters/newsletter_04_Apr2019.md
Announcement for book dashes as discussed in #341 
> Create book dash announcement newsletter

- workshops/book-dash/selection-criteria
- workshops/book-dash/selection-criteria.md
Create a public statement of the selection criteria we will use to assess applications to the Turing Way.
The Turing Way core team will need to assess applications to the Turing Way book dashes to be held in May 2019, this file outlines the selection criteria we will use to do this.
Fixes #<NUM> 
* New file outlining the selection criteria for assessing applications to the Turing Way book dashes
> Create selection criteria for book dashes

- workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md
Fixes #335  
Updating the Build a BinderHub Workshop.
This generalises the bitly link (gets rid of my initials!) and adds a table of contents at the top of the resource.
* Updated bitly link
* Table of contents
> [Quick Fix] Update Build a BinderHub Workshop

- workshops/book-dash/application-form.md
Added the fields we added to the form ad hoc to have a complete record and make this actually useful to re-use. Also fixed the Manchester date.
* Just syncing this with the actual form used
> Add name and email address

- project_management/tps-funding-application-20190429.md
Minor stuff, mainly some inconsistencies in structure of bullet points and other phrasings that my brain struggled with
Accept or decline, hope this doesn't mess with the word count too much
> Some rewording suggestions

- project_management/tps-funding-application-20190429.md
My attempt to cut :smile: + a typo fix
> Cut research challenges section to 300 words

- personas.md
This document describes the personas and pathways for contributors and users to guide the development of the Turing Way following [Mozilla Open Leadership training](https://mozilla.github.io/open-leadership-training-series/articles/building-communities-of-contributors/bring-on-contributors-using-personas-and-pathways/). Specifically, it will help us identify any barriers to contributing in the Contributing Guidelines and README. It is based on the personas.md document in the [Open Leadership Framework repository](https://github.com/mozilla/open-leadership-framework/blob/master/personas.md).
Related to #403  
To do:
> [WIP] Add personas & pathways

- workshops/boost-research-reproducibility-binder/workshop-presentations/instructor-guide_zero-to-binder.md
- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-solo.md
This PR addresses the comments @LouiseABowler gave in PR #358 but I was unable to fix them in the same PR due to the git history rewrite.
* Comments from Louise
> [Ready for Review] [MRG] Update binder workshop

- README.md
Doesn't fix an open issue.
Removed sentence in README that referenced the book repository.
> [Quick fix] Remove reference to book repository

- .all-contributorsrc
Tidying up the contributors table in the README
> Put contributors in alphabetical order

- CONTRIBUTING.md
Fixes #446  
This PR adds some instructions on how to add contributors using the [all contributors bot](https://github.com/all-contributors/all-contributors) to the [Contributing Guidelines](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md).
> [Ready for Review] Updated CONTRIBUTING with all-contributors bot instructions

- project_management/dissemination-report-20190507.md
This PR updates the list of contributions to Binder from #96 into the dissemination report.
* Add links to PRs to Binder opened by core Turing Way team members
> Update list of PR contributions to Binder

- workshops/book-dash/before_workshop.md
Info to be sent out to attendees before the book dash as laid out in #399 #397 #398 
Initial drafts for both emails
> [Ready for review] Pre book dash comms

- book/content/rdm/rdm.md
Embarrassingly petty change - replacing "regularly" with "frequently" where relevant.
* regular = constant frequency, occurring at predictable intervals
* frequent = often, many times
> regularly -> frequently

- book/content/collaborating_github/collaborating_github.md
- book/content/open_research/open_research.md
- book/content/version_control/version_control.md
Addresses #435 
I will add in the links to the following chapters:
- Open Research
- Collaborating on GitHub/GitLab
Clare Liggins
> Added a link to the version control prerequisite

- book/content/collaborating_github/collaborating_github.md
- book/content/continuous_integration/continuous_integration.md
- book/content/make/make.md
- book/content/open_research/open_research.md
- book/content/rdm/rdm.md
- book/content/reproducible_environments/reproducible_environments.md
- book/content/reviewing/reviewing.md
- book/content/testing/testing.md
- book/content/version_control/version_control.md
Fixes #435  
I will add in the links to the following chapters:
- Version Control
- Reproducible environments
- Testing
- Reviewing
- Continuous integration
- Research Data Management
- Reproducible Research with Make
> [Ready for review] Adding in prerequisite links

- CONTRIBUTING.md
Fixes #487
Relative links are needed to link between chapters within the book, this PR explains how to do this.
* Adding text to the contributing guidelines to explain how to add relative links
> Added relative links to contributing guidelines

- .all-contributorsrc
Doesn't close an open issue
Rearrange the contributors to be alphabetical order.
* Move folks around in the json file
> Alphabetise the contributors

- book/content/collaborating_github/collaborating_github.md
Fixes #<NUM> 
Proofread and updated this page.
The following updates were made:
changed formatting of README to be consistent
updated bullet points to be consistent
added in commas
updated sentence structure for clarity
corrected grammar and spelling
> [Ready for review] Proofread Collaborating on GitHub/GitLab page and made updates

- .travis.yml
> Fix travis bulds

- .travis.yml
No related issues. (related to #540 and #533)
- Document .travis.yml
> Document travis build file

- .travis.yml
- book/content/reviewing/reviewing.md
- scripts/lorem-ipsums.py
* Fixes #538 
* Removes lorem ipsums from reviewing chapter (made into comments instead where I thought that they might be helpful for formatting). 
* Added CI test (lorem-ipsums.py) to test the book for any missed lorem ipsums. 
* Updated travis file to add the above CI test.
As in summary.
> [Ready for Review] Removed lorem ipsums 

- book/content/open_research/open_research.md
Fixes #560 
Removed latin abbreviations
[x] changed e.g. to "for example"
[x] removed etc. and expanded EDI list
> [Ready for Review] Removed latin abbreviations

- book/README.md
extended docs for locally building the book, cf. #548 
* *make people avare of virtualenv to not clutter their system python.*
* *make jekyll/budler dependencies explicit.*
> [ready to review] added a few more details to describe potentiallly missing dependencies

- book/content/reviewing/reviewing.md
- scripts/lorem-ipsums.py
Adds a useful error message to lorem-ipsums.py CI test (have tested the test and it works)
Fixes #564 
As above.
> [Ready for Review] Added more useful error message to lorem-ipsums.py CI test

- .travis.yml
Testing Travis Build Matrix to separate out different tests. Will be useful @NatalieThurlby 's latin-text checker.
> Try out matrix build

- CONTRIBUTING.md
Fixes #580 
Updating style guide in contributing guidelines to make clearer how to link to figures.
> [Ready for review] Updating Contributing Guidelines

- book/content/Ethical_Decisions/Planning_Research.md
Addresses an aspect of, does not fix #552 
This is a sub chapter to Ethical Decisions chapter and Planning Research.  Unsure as to how this will fit in the final structured chapter but have written as stand alone and very happy to edit accordingly in future
[x] for preclinical scientists to use EDA for planning animal experiments
> [Ready for Review] Ethical Desicions_Planning_Research

- README.md
Moving figures and stuff around broke the image link in the README, so I fixed it!
* Fix team photo in README
> Fix team photo in README

- README.md
Fixes #597 
* Acknowledges newbie fears
> [Ready for review] Acknowledge new user fears

- communications/newsletters/newsletter05_May2019.md
Draft of a May/June newsletter.
Fixes #545 
* Draft newsletter added in communications/newsletters/ folder
> Draft May newsletter

- CONTRIBUTING.md
> [FIX] add https to prettier.io

- CONTRIBUTING.md
Fixes spelling error and typo for Somersault 1824 link in CONTRIBUTING.md
> [Ready for review] Fixed typos in CONTRIBUTING.md

- book/content/continuous_integration/continuous_integration.md
This pull request removes the latin abbreviations in continuous_integration.md 
*Addresses (but does not close) #588*
the-turing-way/book/content/continuous_integration/continuous_integration.md
> Edited a few latin abbreviations in reference to #588

- project_management/online-collaboration-cafe.md
Doesn't close an open issue
First draft of project management documentation explaining proposed online Collaboration Cafes in autumn 2019.
* Description, dates and times for online collaboration events in autumn 2019
> [Ready to review] Documentation for online Collaboration Cafes in autumn 2019

- project_management/impact_statements/patricia_herterich.md
This PR adds my impact statement to project_management/impact_statements/ as requested in #461
* My impact statement added under the project_management/impact_statements/ folder
> Add Patricia's impact statement

- workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md
Tiny PR to update the links to specific lines in `setup.sh` to point to `master` to avoid future 404s.
* hyperlink updates
> Update line links in setup.sh to point to master

- communications/newsletters/newsletter_06_Sept2019.md
Doesn't close an open issue
* Saw a mistake right as I clicked merge. DOH!
> [Quick fix] Fix broken links

- workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md
Fixes minor typo in code to paste to activate Sponsorship subscription
* Missing double quotes added
> Minor typo

- project_management/online-collaboration-cafe.md
Doesn't close an open issue
Added the youtube links to the collaboration cafe overview and schedule page.
* Added youtube links 📽
> [QuickFix] Add youtube links to collaboration cafe page

- book/content/reproducibility/04/barriers.md
Doesn't close but does address in part #696.
Minor update to the introduction text.
* The beginning of this section links to the talk I gave at csv,conf.
I think it makes sense to link to the slides too 😸
> Add link to slides in barriers to reproducible research section

- book/content/reproducibility/04/barriers.md
> Add barrier 1 (plead the fifth) to barriers.md in reproducibility chapter

- CONTRIBUTING.md
*Fixes typo in the contributing document and removes trailing spaces*
* *Fix typo of "un" to "in"*
* *Fix typo of "form" to "form"*
* *Remove trailing spaces*
> Fix contributing typo and remove trailing spaces

- LICENSE
- LICENSE.md
Fixes #718 
This repository contains some software code to build and host the book (as a jupyter book) on netlify but also a lot of written content that should be available under a creative commons license.
This PR updates the licence file to clarify that point.
* Make licence file link to both CC-BY and MIT licence text
> Update licence to include both MIT and CC-BY

- README.md
Just added the new section to the ToC to increase visibility
* Added new section to ToC
> Add citing section to ToC

- README.md
Added in link to podcast summary of the Turing Way from the Open Science FAIR, doesn't fix an issue.
* Added link to podcast
> Add in podcast link

- README.md
Adds a link to the gitter room mirror on matrix.org.
> Add link to #the-turing-way:matrix.org

- book/content/reproducibility/02/whycare.md
*For a list like this, I expected that the key points would be
emphasized. So this commit makes the key reason bold for easier skimming
and reading.*
* *Bolds the text of the key reasons.*
> Emphasize key reasons for reproducibility

- book/content/version_control/version_control.md
Fixes #752 
* *replace underscores with hyphens in correct anchors (2 in total)*
* *make sure anchors that pointed to non-existing headings to existing headings (2 in total)*
Anchors now work in the GitHub rendered .md files.
- @KristijanArmeni
> Version control heading anchor

- book/content/collaborating_github/3/getting_contributors.md
Signed-off-by: Pooja Gadige <poojagadige@gmail.com>
Sub-topics of **Getting Contributors** section are missing from the TOC located on the right.
Fixes #402 
* *Level down the headings of sub-topics to heading level 3*
* Look out for the list of sub-topics to appear in the TOC located on the right of the page
* The sub-topics are: Personas and pathways, Code of Conduct and Contributor Guidelines
> Level down sub-topics to heading level 3

- book/content/credit/credit.md
Minor typo fix.
* *New full stop.*
> typo - add full stop

- book/content/introduction/introduction.md
> minor typo - full stop

- book/content/make/make.md
- book/content/open_research/01/opendata.md
- book/content/rdm/rdm.md
- book/content/reproducible_environments/01/options.md
- book/content/reproducible_environments/02/package-management.md
- book/content/reproducible_environments/03/yaml.md
- book/content/reproducible_environments/06/containers.md
- book/content/reproducible_environments/reproducible_environments.md
- book/content/testing/testing.md
- book/content/version_control/version_control.md
This PR aims to replace the remaining latin abbreviations in book chapters.
Closes #588 
Replaced latin abbreviations from the following chapters:
> [Ready for review]Fix the remaining latin abbreviations

- workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md
How authentication is configured in the helm chart has changed to be more concise. This PR updates the Zero-to-BinderHub workshop to reflect this more concise config.
* Zero-to-BinderHub workshop
> [Ready for Review] Update Zero-to-BinderHub workshop

- .all-contributorsrc
- project_management/jupyter-workshop-application-20191215.md
Closes #770 
* Funding application written by @trallard & @KirstieJane
> Jupyter Workshop application

- communications/newsletters/newsletter_09_Jan2020.md
Minor fix, just added a link
* Add link
> Add Repro2020 workshop link

- book/content/version_control/version_control.md
Fixes #796
Link to Git cheatsheet was broken and gave a 404 error.
* fix broken git cheat sheet link
* [additional small tweaks] Remove trailing whitespace from version control document and fix typo
> Issue #796 fix broken link in version control

- LICENSE.md
Fixes no open licence
There's a missing parenthesis - this PR fixes it!
* Add `)`
> Fix typo in licence

- workshops/boost-research-reproducibility-binder/agenda.md
Fixes path separator typo
* *Fixes path separator typo in `workshops/boost-research-reproducibility-binder/agenda.md`*
> fix: path separators

- CONTRIBUTING.md
Contribution guideline with the updates on code of conduct, and contact info. A few suggestions on the language.
> A few suggestions with the contact update

- book/content/reproducibility/04/barriers.md
It adds the _takes time_ section to `barriers.md` file #696.
Paragraph addition
> Add barrier 6 (takes time) to barriers.md in reproducibility chapter

- project_management/online-collaboration-cafe.md
* Date updated till March
* video column removed
* YouTube Channel added
> Updated Collaboration Cafe table for 2020

- conferences/abstracts/2020-03-10-DataSciencePerspectivesConference.md
Abstract for a session during the Data Science Perspectives conference in New Castle on March 11, 2020.
> Workshop abstract: Data Science Perspectives conference in Newcastle, March 11

- book/content/reproducible_environments/06/containers.md
This PR addresses various issues with the Docker guidance on the Containers page of the Reproducible Environments chapter.
Fixes #810
* Addresses some incorrect commands and typos
* Implements some best practices (with explanations)
* Generally tidies up the relevant content.
> Clarifications, corrections and simplifications for Containers page

- book/content/reproducible_environments/02/package-management.md
Conda list command is added. It displays the list of installed packages in the Conda environment.
It can also be utilised to check if a particular package exists in the environment. 
In my opinion this is one of the most essential commands in a package manager.
* Adds `conda list` to see all of the installed packages
* Adds `conda list scipy` to check if a specific package of interest (scipy in this case) exists in the environment
> Chapter 8.2: added Conda list command to see installed packages

- book/content/reproducible_environments/02/package-management.md
After having read the chapter I found it hard for the readers to understand how Conda is keeping track of the packages installed through `pip`. Also the current explanation is not always correct as one can install `pip` outside a Conda environment [1].  
References:
1. https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-pkgs.html#installing-non-conda-packages
* Clarifies under which condition conda tracks `pip` packages
> Chapter 8.2: Clarification on Conda-pip integration

- .all-contributorsrc
Fixes #776 
There was an update to the configuration file format in December and I think that is why we haven't been able to add anyone to the all contributors table!
* Reformat file according to https://allcontributors.org/docs/en/bot/configuration
> reformat all contributors file

- book/content/open_research/04/openaccess.md
PR on the original #797
* Updated link formatting for SHERPA/RoMEO
> Typo/bug fix in openaccess chapter edit by Esther Plomp

- book/content/credit/credit.md
Fixes #863
* * Adding information about ORCID to the credit section
> [Ready to review/merge] Update credit.md with information on ORCID

- book/content/reproducibility/03/definitions.md
Fixes #802 
This PR explicitly defines the different dimensions of reproducibility presented in the grid in the [definitions](https://the-turing-way.netlify.com/reproducibility/03/definitions) section of the book.
* Explicitly write out definitions of reproducibility
> [RVW] Expand definitions of reproducible research

- book/content/credit/credit.md
- book/content/reproducible_environments/06/containers.md
Removing some rogue latin phrases to appease CI
* Remove rogue latin
> Remove bad latin phrases to fix CI

- book/content/reproducibility/02/whycare.md
Minor language correction in the Reproducibility chapter
> Why reproducibility: minute change in language

- book/content/rdm/rdm.md
- shortened information that is not directly relevant or applicable
- added some extra examples
Fixes #887
> [Ready for review] Update RDM

- book/content/reproducibility/reproducibility.md
Certain parts in the introduction seemed misplaced and repetitive. In this PR I have moved around a few sentences to start the introduction chapter clearly.
* Moving a sentence of the Turing Way's definition of reproducibility
* Replace science with research
* Removed the redundant disclaimer of why The Turing Way's definition is given
> Formatting the introduction chapter

- book/content/naming/naming.md
Addresses #886
* Add chapter on naming files, folders and other things
> [Ready for review] Chapter on naming 

- book/content/open_research/01/opendata.md
***This pull request has been identified as suitable for review by a first time reviewer. If you don't feel confident reviewing PRs but would like to learn please ask any questions as you do your review!***
If you *are* confident reviewing pull requests please consider finding a different PR to review and leave this one for first time contributors 💖 
Fixes #835 and adds new line after each sentence (see contributing guidelines).
* Add links to RDM chapter, mention FAIR
* Add new line after each sentence
> [Ready for review] Improve open data chapter, links to rdm (see #835)

- project_management/online-collaboration-cafe.md
* Included April dates
* Checked the time zones
> [MRG] Add April dates for collaboration cafe

- book/content/research_compendia/research_compendia.md
Fixes #950 
This PR fixes some minor typos for the research compendium chapter. 
[x] Fix typos identified in #950
> Fix some typos for research compendia

- book/content/introduction/introduction.md
Fix small typo in Introduction chapter.
> We really appreciate any references that you make to The Turing Way project in your and we hope it is useful.  
to  
> We really appreciate any references that you make to The Turing Way project in your work and we hope it is useful.
> Fix small typo

- book/content/remote_collaboration/checklist/checklist.md
To thank you for providing this super-useful list, I went through and copy-edited it. (I hope that's helpful and not annoying!)
One thing I noticed is a lot of redundancy. In many cases, I got tired of editing the same phrase over and over and just left it alone. :-)
You might consider improving the maintainability of this document by leaving out some of the repeated points and referring the reader to other sections, as you did here, for example:
> Share the link of the gallery where the pre-recorded lightning talks are posted along with the shared notes from the session (see details in (Program (before the event))
Fixes #<NUM>
* *Lorem ipsum dolor sit amet, consectetur …
> fixed typos, improved some wording

- book/content/licensing/01/softwarelicenses.md
* Removing i.e. from the license chapter
> Remove  i.e. from the license chapter

- book/website/_data/toc.yml
Fixes #<NUM>
* link for rdm and license corrected by adding '/'
> link for rdm and license corrected

- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-solo.md
- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder.md
This PR updates the Zero-to-Binder tutorial(s) (python version). The changes are mostly just markdown linting, synchronising between the two files and tweaking some language.
* Updates to `zero-to-binder.md` and `zero-to-binder-solo.md`
> Update zero to binder tutorial (python)

- README.md
This PR collects together the status badges of all of our tests together into a table so it can easily be seen which ones are failing.
* Added GitHub Actions status badges to README
* Collected all status badges together into a table
> [MRG] Add table of test status badges to README

- book/content/credit/credit.md
- book/content/licensing/01/softwarelicenses.md
- book/content/rdm/fairprinciples.md
- book/content/rdm/sharingarchiving.md
This PR changes some latin phrases so that our tests pass.
* e.g. --> for example
* i.e. --> that is
> [MRG] Remove bad latin phrases so CI passes

- .all-contributorsrc
Fixing some typos in the .all-contributorsrc file.
* .all-contributorsrc
> [Ready for Review] Correct issues in all-contributorsrc file

- book/content/credit/credit.md
- book/content/introduction/introduction.md
- book/content/reproducibility/01/importantforscience.md
- book/content/reproducibility/02/whycare.md
- book/content/reproducibility/03/definitions.md
I did a light editing pass on the first two chapters, mostly correcting typos but I did reword a couple of sentences I found unclear.
* Correct tenses of "generalisability" to match the diagram
* Fix typos.
* Clarify a couple of sentences.
- Make sure I didn't make new spelling mistakes >_<
> Light edit

- book/website/_data/toc.yml
* Updated toc to add code quality chapter correctly in the book
> toc.yml updated to add '/' 

- CONTRIBUTING.md
Fixes #467 
*Updated the issue labels section of the contributing guidelines to add new/edited labels*
-  [x] *Cross checked the Issue labels section with the master list of labels.*
-  [x] *Add, edit or remove labels as necessary.*
-  [x] *Sorted in alphabetical order.*
> [Ready for review] Update issue labels in CONTRIBUTING.md

- book/content/figures/figure_list.md
* Updated images for 
* why care about reproducibility
* research compendium
* Name in the image list added
> figure_list.md: Update missing image names

- project_management/online-collaboration-cafe.md
Update the description of the Collaboration Cafe
* Updated description of these calls
> Update  the opening line of Collaboration cafe doc

- .all-contributorsrc
Addresses (but does not close) #992
Manual addition to the all contributors json file
* A bunch of updates to the all contributors json file
Note that these updates are not all of the ones listed in #992 - but I'd like to merge this to master to see if I can get the bot working 🙏 
Please merge this so I can get the bot to format the README file :)
> Cleaning up the contributors table

- .all-contributorsrc
Hot fix - I had a spare `+` in the json file
> All contribs 20200410

- .all-contributorsrc
Hopefully this will stop travis from getting so upset
> Turn off skipping continuous integration for all contributors bot

- .all-contributorsrc
* Remove duplicated entry from contributor's list
* remove 2nd entry for mateusz
> removing duplicated Mateusz

- .all-contributorsrc
The PR sorts the contributors table alphabetically. MASSIVE thanks to @alexwlchan for that contributions to All Contributors! all-contributors/all-contributors-cli#249
> Sort all contributors table alphabetically

- book/content/credit/credit.md
Adding a section on the importance of persistent identifiers to the credit for reproducible research chapter. 
Does not address an open issue
* New text on why PIDs matter and why you should get a DOI for your research outputs
> WIP - Add section on DOIs and ORCIDs to Credit chapter

- book/content/5-book-preview/5-book-preview.md
- book/website/_data/toc.yml
- book/website/_redirects
- It test redirects on a test chapter
* A new link added to website/_data/toc.yml (last lines)
* A _redirects file has a redirection for this test to the preview of #977
> test simple redirect

- book/content/diving_into_leadership/diving_into_leadership.md
This PR is applying Malvika's comments on my Leadership blog that I merged too early to incorporate 😬 
* Language tweaks in the leadership blog
> Apply Malvika's review comments to Leadership blog

- book/content/continuous_integration/continuous_integration.md
I added some more suggestions on setting up CI based on [the SSI blog post](https://software.ac.uk/blog/2020-02-27-continuous-integration-fail-fast-and-fail-first) I co-authored with @sgibson91. Along the way I made some changes for readability and to fix typos.
* clarify wording of benefits to using CI
* reduce use of passive voice
* explain why failing to use CI makes collaboration difficult
* don't mention that something isn't discussed here when it is
* warn against zealously allowing test failures
* recommend organising the pipeline to fail fast
> Ci chapter

- book/content/reproducibility/01/importantforscience.md
- book/website/_bibliography/references.bib
Added 2 citations in Chapter 2.1 to contribute to #889
*  Citation for Baker 
*  Citation for Dirnagl & Lauritzen
> Added citations for 2.1

- .github/config.yml
- README.md
Fixes #860 
This pull request is configuring the [behaviorbot/welcome](https://github.com/behaviorbot/welcome) probot app on the repo. This bot will leave a comment when first-time contributors open a new issue/pull request and successfully merge their first pull request. The idea is to make them feel welcomed to the community and provide any additional info on where they can get help if they need it.
* Added `.github/config.yml` containing the welcome bot config
> [Ready for Review] Add welcome bot

- book/content/open_research/01/opendata.md
- book/content/open_research/02/opensourcesoftware.md
Fixing the typo, Link issue and a wordage issue. 
* *Simple PR to fix small typo and Link*
> Typo and Link Fix

- book/content/open_research/01/opendata.md
- book/content/open_research/02/opensourcesoftware.md
- book/content/open_research/07/resources.md
- book/content/rdm/docmetadata.md
- book/content/rdm/spreadsheets.md
- book/content/rdm/storagebackup.md
- book/content/reproducibility/02/whycare.md
**Trying to solve Broken Links.**
There are a couple of broken links, instead of separate PRs, trying to create a single PR regarding it.
Basic Link Fixes
> [WIP] Fixing a ton of broken links

- CONTRIBUTING.md
Fixes #794 and #846 
* Broken ISSUE_TEMPLATE link
* Also added links for 
1.    New Chapter Template
2.    General Issue
3.    Bug Report
> Added ISSUE_TEMPLATE link in CONTRIBUTING.md

- book/website/assets/html/search_form.html
Fixes #1114 
* Correcting search box text so that it appears correctly
* The search option displays only partially -"'Enter the search ter"
* The previous text is changed from "'Enter the search term...'" to "Enter the search term"
> correcting search box text

- README.md
> update emoji key reference

- CONTRIBUTING.md
A couple of pesky extra brackets
> fixing md formatting in contributing file

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
*Fixes #1127 . Fixed [this](https://github.com/alan-turing-institute/the-turing-way/blob/master/.github/ISSUE_TEMPLATE.md) link.*
* *Added the label for [good first PR review](https://github.com/alan-turing-institute/the-turing-way/labels/good%20first%20PR%20review) in [CONTRIBUTING.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md)*
* *Added [issue template](https://github.com/alan-turing-institute/the-turing-way/blob/master/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md)  link in [this](https://github.com/alan-turing-institute/the-turing-way/blob/master/CONTRIBUTING.md#1-comment-on-an-existing-issue-or-open-a-new-issue-referencing-your-addition) section.*
> Add label in CONTRIBUTING.md, fix broken link

- book/website/open_research/01/opendata.md
- book/website/open_research/open_research.md
Fix broken links for sections 3.1.2, 4.5, and 12 in the Open Research
chapter.
Fixes #1125 
* *Add correct link for section 3.2.2, [National and commercially sensitive data](https://the-turing-way.netlify.app/rdm/sharingarchiving.html#national-and-commercially-sensitive-data).*
* *Add correct link for section 4.5, [How to contribute to other’s open source software projects](https://the-turing-way.netlify.app/open_research/02/opensourcesoftware.html#how-to-contribute-to-other-s-open-source-software-projects).*
* *Add correct link for section 12, [Definitions/glossary](https://the-turing-way.netlify.app/open_research/07/resources#definitions-glossary).*
> Open Research: Fix broken links

- book/website/code_quality/code_quality.md
- book/website/version_control/vcs-checklist.md
Addresses #1075 
@malvikasharan 
*This pull request is a small self-contained contribution to the Turing Way project under gsod 2020.*
- Overall improved `Code Quality` section
- Static Code analysis section has a new table mentioning all widely used code analysis tools for major languages. Also added the advantages sub-section in the same.
- mentioned standard code guideline of Javascript.
- Introduced two different styles of auto code formatting. Wrote the JSON line need to turn on auto format in VScode(being one of the most famous text-editors out there).
- Fixed typos.
- Auto Formatting Code section has a new table mentioning all widely used beautify tools for different languages.
> Editing and adding content in the code quality chapter

- book/website/reproducible-research/open.md
- book/website/reproducible-research/overview/overview-benefit.md
- book/website/reproducible-research/overview/overview-resources.md
- book/website/reproducible-research/reproducible-research.md
- book/website/reproducible-research/vcs.md
Signed-off-by: pgadige <poojagadige@gmail.com>
Builds up on #977 
Add labels to other chapters and cross-reference those chapters from inside "Overview" chapter.
* Add label: ***rr-open*** to "Open Research" chapter's landing (main) page.
* Add label: ***rr-vcs*** to "Version Control" chapter's landing (main) page.
* Add cross-references for the above labels in Overview -> Resources page
> Add labels to chapters, cross-reference those from inside different chapter

- book/website/community-handbook/style/style-crossref.md
- book/website/reproducible-research/overview/overview-resources.md
> Explain style convention for labels and cross-references

- book/website/community-handbook/coc.md
- book/website/community-handbook/coc/coc-details.md
- book/website/community-handbook/coc/coc-enforcement.md
- book/website/community-handbook/coc/coc-reporting.md
Signed-off-by: pgadige <poojagadige@gmail.com>
Builds on #977 
* *Fix the syntax for defining labels*.
* *Correct a punctuation typo*.
> Fix labels for Code of Conduct subchapter

- book/website/ethical-research/ethical-research.md
Co-authored by: I@Ismael-KG 
* The PR merge lost the changes made by Ismael - adding it back
*  updating last sentence with Ismael's changes in #1206
> Update ethical-research.md section 

- book/website/_toc.yml
Fixes #<NUM>
* Remove research environment subchapter's title from toc.yml
* changes toc.yml file
> Update _toc.yml to remove inconsistent hear/title in the book

- README.md
- tests/no-bad-latin.py
This PR adds an ignore list to `no-bad-latin.py`. This is because there are some files that contain unwanted latin phrases that we don't "care" about: the `_config.yaml` file for the book build, and the style guide which provides examples of unwanted latin phrases. These files are therefore not tested. This pull request will leave one instance of a latin phrase that genuinely needs correcting.
This PR also makes the CI status badges in the readme clickable links that redirect to the logs.
* `tests/no-bad-latin.py`
* `README.md`
> Bugfix: Add an ignore list to no-bad-latin.py

- book/website/_toc.yml
- netlify.toml
- tests/no-bad-latin.py
* The error of file name in CI chapter is fixed with this PR
* toc.yml file -> under CI section
> rename the CI chapters correctly

- book/website/new_file.md
- tests/no-bad-latin.py
This PR fixes a bug in `no-bad-latin.py` that was causing the test to fail when a PR added a new file.
fixes #1215 
* Removed accidentally repeated code block in `no-bad-latin.py`
> [Ready for Review] Fix a bug in our tests

- book/website/reproducible-research/make.md
- book/website/reproducible-research/make/make-casestudy.md
- book/website/reproducible-research/make/make-examples.md
- book/website/reproducible-research/make/make-resources.md
Fixes broken anchor links in the Make example. There are two anchor links here so that we can link to "automatic variables" and "pattern rules" later on, but they didn't have a closing ``</a>`` tag, so the formatting spilled over (note everything is blue):
This was my mistake, so apologies it took so long to spot and fix it! :facepalm: 
* Add closing tags to anchor links in Make example
* Make links to these tags in Case Study functional.
> Fix anchor links in Make example

- CONTRIBUTING.md
Adresses #114
* Add a section in the contributing guidelines how to represent The Turing Way e.g. at conferences
> A first idea on how to guide people to represent TTW

- CONTRIBUTING.md
Fixes #1244 
added missing step in build instruction (cd to book/website)
> [Ready for Review] Update CONTRIBUTING.md

- book/website/project-design/persona-creation.md
* There are minor changes proposed in this PR
* A few changes to make some sentences more clear
> Update persona-creation chapter with minor update

- book/website/community-handbook/coc/coc-enforcement.md
* remove latin words from the CoC to stop CI from complaining
* i.e. and etc. removed from CoC enforcement manual
* It should allow the CI to pass
> remove latin words from the CoC to stop CI from complaining

- book/website/requirements.txt
Fixes all python package version in book/website/requirements.txt to the state of 2020-07-10, see discussion in #1256 
* modify book/website/requirements.txt
> [Ready for Review] fix python package requirements

- book/website/_bibliography/references.bib
Fixes #<NUM>
* Minor update in the bibliography so it gets referenced correctly in the case studies chapetr
* Capitalised 2 letters as they are being referenced in the chapter
> super minor update in the bibliography

- CONTRIBUTING.md
Just a really tiny typo fix, I just saw.
> Tiny typo fix

- book/website/reproducible-research/open/open-source.md
* Restructures section "How open-source software benefits research"
* structures the section by bullet points and adjectives to summarise bullet points
* adds idea that open source software is checkable by others
* I opened a separate PR for the chapter on toolboxes
> Edit open-source software benefits for research

- .all-contributorsrc
* Fixes the JSON file of the all-contributors bot
* Adding the missing ']', the bug might have been introduced in fixing file conflicts
> Update .all-contributorsrc to add the missing ']'

- communications/promotion-pack/README.md
- communications/promotion-pack/faqs.md
Fixes #1281 
* Adding one-page information with links and info
> Create promotion pack for external representation of the community

- communications/promotion-pack/README.md
Fixes #<NUM>
* Updating the number of contributors which is 175
> minor update in number of current contributors

- book/website/reproducible-research/licensing/licensing-data.md
- book/website/reproducible-research/licensing/licensing-software.md
- book/website/reproducible-research/open/open-access.md
- book/website/reproducible-research/open/open-data.md
- book/website/reproducible-research/open/open-hardware.md
- book/website/reproducible-research/open/open-notebooks.md
- book/website/reproducible-research/open/open-resources.md
- book/website/reproducible-research/open/open-scholarship.md
- book/website/reproducible-research/open/open-source.md
- book/website/reproducible-research/rdm/rdm-fair.md
- book/website/reproducible-research/rdm/rdm-metadata.md
- book/website/reproducible-research/rdm/rdm-resources.md
- book/website/reproducible-research/rdm/rdm-sharing.md
- book/website/reproducible-research/rdm/rdm-spreadsheets.md
- book/website/reproducible-research/rdm/rdm-storage.md
- book/website/reproducible-research/rdm/rdm-stories.md
This would enable relative linking with the new data management plan section
Fixes #1043
* add a relative link for the metadata and documentation section
> update rdm sections with labels for relative links

- book/website/community-handbook/newsletters.md
Just suggested some slight rephrasing in a PR rather than making it a review commetn
Reworded point 1. and 3.
Accept or reject as you see appropriate
> Minor rewording suggestions

- book/website/_toc.yml
* Unpublishes acknowledgement chapter so that Kirstie can review
> Hold acknowledgement chapters for review

- open-life-science-mentoring/README.md
- open-life-science-mentoring/ethical-research-framework/README.md
Related to Ethical research guide
* Creates an OLS folder for the teams to store their notes and files
* creates a dedicated place for OLS projects
* links all the projects that are under OLS-2 for Tuning and shares the GitHub space with the OLS project teams
> create OLS folder and add Ethics project folder

- book/website/community-handbook/acknowledgement.md
* Due to CI fail the acknowledgement chapter was not rendered online. This PR should fix that.
* Acknowledgement chapter appears online in the community handbook
> minor update to the acknowledgement chapter

- contributors.md
Please add Ismael-KG to contributors.md
> add Ismael-KG to contributors.md

- book/website/afterword/contributors-record.md
- contributors.md
- tests/no-bad-latin.py
Fixes #<NUM>
* Minor update in contributors.md and contributors record in the afterword
> Minor update in the Contributor's records to check if CI works

- open-life-science-mentoring/ethical-research-framework/README.md
Added our plan from our Open Canvas exercise as part of OLS-2, about the project that we are doing and the community that we want to build.
> Updated README.md

- book/website/_toc.yml
* The Toc file has been updated to publish acknowledgement chapter and contributors file
*  The Toc file has been updated to publish acknowledgment chapter
> un-comment acknowledgement chapter and contributors file

- book/website/_toc.yml
* Indent the acknowledgement chapter section so that is it it's own chapter and not inside the style guide
* Updated toc file
> Update _toc.yml by correcting indentation issue

- workshops/boost-research-reproducibility-binder/reports/workshop_report_20200131.md
simple update of url to point to new location of image file
> update url to image after changing my GitHub name

- contributors.md
* placeholders are created for each one
* I will suggest these folks pinging each other for this PR and review too :)
> Update contributors.md with Laura, Sophia and Paul's details

- contributors.md
Added my github and orcid links, and short bio.
> Update contributors to add my links and bio

- project_management/online-collaboration-cafe.md
* Adds dates for September in the schedule table
* Adds dates for September in the schedule table
> Update online-collaboration-cafe table with the date and time for 2020

- book/website/reproducible-research/vcs/vcs-git-merge.md
Fixed a minor syntax error. 
* Deleted a space that prevented text from rendering in bold.
> Fix minor Markdown syntax error

- contributors.md
> Added bio in contributors.md

- contributors.md
Updated contributions of eScience center & short bios of @mkuzak and me. More to be added later.
Contributes to #1357
None.
* Adds missing information as from eScience center collaborators
> Updated eScience center contributions

- book/website/project-design/persona/persona-contributors.md
- book/website/reproducible-research/open/open-source.md
Fixed Markdown Formatting of non consecutive headers in the file project-design/persona/persona-contributors.md and reproducible-research/open/open-source.md
Fixes #1412 and #1411 <NUM>
- Update persona-contributors.md 5b2e49f
- Update open-source.md 9c5948a
> Fixes Markdown formatting of non-consecutive headers: persona-contributors.md , open-source.md

- book/website/collaboration/new-community.md
updated Markdown code to MyST for Fig 2 in chapter Managing a New Community and Team  according to style guide
Fixes #1416
converted all figures in chapter to MyST format
* new-community.md file updated figure 2 to MyST format
> updated Fig.2 in chapter Managing a New Community and Team to MyST format

- book/website/reproducible-research/open/open-access.md
Fixes [#1406](https://github.com/alan-turing-institute/the-turing-way/issues/1406)
* Fixed Markdown formatting of non-consecutive headers in the file open-access.md
* Decreased all headers by one level (h2 -> h1, h3 -> h2 and h4 -> h3)
> Fix non-consecutive headers: open-access.md

- book/website/reproducible-research/vcs/vcs-git-merge.md
fixed header tags; added syntax highlighting
References #1424
- fixed heading
- add syntax highlighting (python, bash)
@malvikasharan @KirstieJane
> fixed format (header, add syntax highlighting) vcs-git-merge.md

- book/website/reproducible-research/vcs/vcs-github.md
Adresses #1424 
Updated heading labels.
> Changed heading labels from 4 to 3 and 3 to 2 in vcs-github.md

- book/website/afterword/contributors-record.md
Fixes #<NUM>
Corrected a mistake I made in the `Personal Highlights` and `More Infomation` sections of my profile from a previous update.
* The last sentences in the Personal Highlights and More Information sections of Paul's profile were switched, to make the text more coherent.
> Correcting Paul Owoicho's contributors record

- book/website/reproducible-research/rdm/rdm-resources.md
Fixes #1404 
* Added a top header to rdm-resources.md - 'Resources'
* Added a short summary to the chapter under the top header
> Fixed formatting on rdm-resources, added header and chapter summary

- open-life-science-mentoring/README.md
- open-life-science-mentoring/accessible-guidance/README.md
* Update the participant's name and their project links in the repo
* Links work
* All the people are added
> update OLS project details with right links and names

- book/website/welcome.md
Fixes #1174 
In this PR, I edited the welcome page of the book to ensure consistent grammar and tone. I also converted the image from markdown to MyST
* Edited to ensure good, consistent grammar
* Updated image from markdown to MyST format
> Retrospective consistency for welcome.md

- book/website/reproducible-research/reproducible-research.md
Partially Fixes #1174, moved from 1340
With this PR, I fixed a typo in the landing page of the guide to reproducible research and updated the image from markdown to MyST format
* Typo fix
* Converting image from markdown
> Typo Fix and Image conversion to MyST

- communications/GSOD-applications/2020-Paul-Owoicho/README.md
- communications/GSOD-applications/2020-Paul-Owoicho/check-in.md
* Storing updates from GSoD 2020
* Create a folder for 2020
* Add files with summary
* Create a folder of OLS-updates
> This PR creates a directory to store GSoD 2020 related updates

- book/website/reproducible-research/case-studies/statistical-methods-manuscript.md
Fixes #<NUM>
* The case study needed to be updated upon discussion with KW
* If the structure of the case study looks ok - @pgadige can look at it to help structure the template for case studies
* What information is missing that should be added
> Update the format of the case study

- book/website/reproducible-research/overview/overview-definitions.md
> Fix citation

- book/website/_toc.yml
- book/website/reproducible-research/rdm.md
- book/website/reproducible-research/rdm/rdm-checklist.md
- book/website/reproducible-research/rdm/rdm-data.md
- book/website/reproducible-research/rdm/rdm-fair.md
- book/website/reproducible-research/rdm/rdm-metadata.md
- book/website/reproducible-research/rdm/rdm-resources.md
- book/website/reproducible-research/rdm/rdm-sharing.md
- book/website/reproducible-research/rdm/rdm-spreadsheets.md
- book/website/reproducible-research/rdm/rdm-storage.md
- book/website/reproducible-research/rdm/rdm-stories.md
Related to #1174, moved from #1396
This PR addresses some of the consistency issues highlighted in issue 1174 for the Research Data Management chapter of the Guide to Reproducible Research. (This branch is up to date with my master branch, so it carries those changes as well)
> Retrospective Consistency on RDM chapter of Guide to Reproducible Research

- book/website/reproducible-research/open/open-notebooks.md
> Fixed heading level in open-notebooks.md issue #1409

- book/website/reproducible-research/open/open-data.md
Fixes #1407 
*Fixes non-consecutive headings in open-data subchapter*
* Dropped heading levels by one*
> Fixed non consecutive headers in open-data.md

- book/website/reproducible-research/open/open-resources.md
Related #1405
* It corrects the header levels
* Instead of h3 -> h2, and h2 -> h1
> Update open-resources.md with correct header

- book/website/reproducible-research/ci/ci-checklist.md
Fixes #1529
Addresses two of three item of the items of the checklist
* Remove the level 2 Checklist header (## Checklist)
* Remove the square brackets from each checklist item ([ ])
Possible improvements may be to add parsing of checkboxes (e.g. [ ]) or nested check marks (eg. {fa}`check,text-success mr-1`) to the jupyter-book project.
> Consistency in ci-checklist.md

- book/website/reproducible-research/make.md
* Changed ## An Introduction to Make to ## Why This is Useful
* Changed ## Prerequisites / recommended skill level to Prerequisites
* Checked for correct grammar
> Review the make.md chapter

- book/website/_toc.yml
- book/website/reproducible-research/rdm/rdm-toolkits.md
* Adding a new subchapter on rdm toolkits, rdm-toolkits.md
* News subchapter for rdm
> Adding a new subchapter on rdm toolkits

- README-French.md
> Jessyprovencher master

- book/website/reproducible-research/credit.md
Fixes #<NUM>
* removed square brackets between row 190 and 205
* row 127 syntax?
* ORCID iD/ID?
* added full stops, capitalised letters
> Reviewed credit.md chapter

- book/website/afterword/glossary.md
Here is the update for the glossary to put all keywords in the afterword rather than at the end of the chapters.
Fixes #<NUM>
> first update of glossary

- .github/ISSUE_TEMPLATE/CHAPTER_ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
Fixes #<NUM>
The current set of templates for issues need a bit of improvement. In this PR, I make some suggestions so that newcomers can better raise issues for the community.
> Update the Current Set of Issue Templates

- book/website/_bibliography/references.bib
- book/website/_toc.yml
- book/website/ethical-research/preclinical-research.md
- book/website/reproducible-research/licensing/licensing-checklist.md
- book/website/reproducible-research/licensing/licensing-data.md
- book/website/reproducible-research/rdm/rdm-sharing.md
Updated list of references with DOI-linked bibliography in intro to Ethical Research
There are still some referenced articles/blog posts not listed here from the new intro. @malvikasharan, as we discussed, you have the list. Thanks so much for your help!
> Update list with new bibliography from intro to Guide for Ethical Research references.bib

- .all-contributorsrc
- README-translated/README-French.md
- There was an error due to a merge conflict in the .all-contributorssrc . This should fix it.
- moving README-French.md to README-translated
> Update .all-contributorsrc for a minor JSON error and move French README to README-translated

- book/website/community-handbook/style/style-citing.md
Fixes #1581 
- Add direct link to bibliography for easy access
- Replace dash with em dash
- Indent bibliography directive to render correctly
- Differentiate similar named section
- Link to Sphinx BibTeX extension
- Add explanation for BibTeX files and share tools
> Clarify bibliography page

- book/website/afterword/glossary.md
Fixes #<NUM>
Several typos are corrected and an amendment has been done in one of the definition in the glossary. 
Several typos are corrected and an amendment has been done in one of the definition in the glossary. 
Whether the correction and amendment made suits with the aim of the glossary or not.
> Typos and Definition addition

- book/README.md
Fixes #<NUM>
I updated the Content Templates section of the book README to reflect the recent changes in the templates directory
* Updated the content template section
> Update Content Templates section of README

- book/website/community-handbook/style/style-crossref.md
Fixes #<NUM>
The label for the Communications Guide is missing. I have updated it accordingly
* Changed Contribution to Communication and added a `cm` label
* Changed `clb` label to `cl`
> Update label for Communications guide

- book/website/_toc.yml
- book/website/afterword/afterword.md
- book/website/afterword/glossary.md
- book/website/community-handbook/acknowledgement/acknowledgement-members.md
- book/website/community-handbook/style/style-more-styling.md
- book/website/reproducible-research/binderhub/binderhub-build.md
* Testing if the glossary format of JupyterBook can be used
*  Update the glossary page
* Update style guide with description on how to crosslink glossary
> Format glossary with JupyterBook standard

- book/website/_bibliography/references.bib
- book/website/reproducible-research/renv/renv-resources.md
> Change link from preprint to paper

- CONTRIBUTING.md
In the guide on writing a chapter, there was no direct link to the chapter template and it was hard to find.
* added a direct link to the chapter template developed by @paulowoicho
> Added a link to the new chapter template to the contribution guides.

- book/website/project-design/filenaming.md
Fixes #1546
* Removed the square brackets from each checklist item
* Replaced :x: and :heavy_check_mark: icons with {fa}``
> Consistent formatting in project-design/filenaming.md

- book/website/_toc.yml
Fixes a tiny typo in the TOC of the book
> ✏️ Fix a typo in TOC

- book/website/collaboration/easyway/sc1_why_learn_how.md
split up some paragraphs to make it easier to read on a computer, and added some bullet points.
also moved a couple of lines around to make them fit within the section.
edits for readability 
* split up some paragraphs to make it easier to read on a computer, and added some bullet points.
* also moved a couple of lines around to make them fit within the section.
> Feedback on "getting started with GitHub" chapter 

- book/website/_toc.yml
- book/website/community-handbook/style/style-custom-styling.md
- book/website/community-handbook/style/style-special-content.md
Fixes #<NUM>
This chapter is based on work from #1656. Here, I document how to use the book-wide stylesheets in a subchapter in the Style Guide.
> Subchapter on Using Turing Way Stylesheets

- book/website/reproducible-research/open.md
!--
Please complete the following sections when you submit your pull request. You are encouraged to keep this top level comment box updated as you develop and respond to reviews. Note that text within html comment tags will not be rendered.
-->
Partially Fixes #1663
* I replaced the wrong header with "motivation and background"
* I replaced the wrong header with "motivation and background"
> Update the open research chapter by changing heading "Motivation and Background"

- communications/GSOD-applications/2020-Paul-Owoicho/check-in.md
Fixes #<NUM>
In this PR, I document my activities since the last meeting with Kirstie
* Added in my activities since Oct 26th
> Update GSoD Bi-weekly meeting notes

- communications/GSOD-applications/2020-Paul-Owoicho/README.md
- communications/GSOD-applications/GSoD-2020-Project-Report.md
Fixes #<NUM>
This PR uploads the final report documenting _The Turing Way's_ GSoD 2020 activities.
> Final GSoD Report

- book/website/_toc.yml
- book/website/ethical-research/ethics-intro.md
* A chapter was recently merged but it was not added to Toc, and it did not have title.
* Adding title
* Minor formatting of the chapter to remove unused sections
* Adding to toc
> Update ethics-intro.md to include in the book and add a title

- book/website/ethical-research/ethical-research.md
> added (er)= to top of one .md file

- book/website/_bibliography/references.bib
adds reference for  #1267
* *Add reference to the personal.md section (Meyer 2018)
> Update references.bib with Meyer 2018

- book/website/collaboration/remote-collab/remote-collab-meetings.md
I was reading the book, and thought it would be nice to have a couple of links here.
- Add links to Google docs and HackMD
- Correct "Hackmd" > "HackMD"
> Add links to note-taking platforms

- book/website/reproducible-research/credit.md
Fixes #<NUM>
Doesn't fix an issue but adds a resource to the ORCID part of the section
* Add information on how to use your ORCID and an Rpackage to create a CV, saving you time!
> Update credit.md with ORCID cv

- book/website/_toc.yml
- book/website/reproducible-research/rdm/rdm-data.md
- book/website/reproducible-research/rdm/rdm-dmp.md
Update table of content with the new subchapter on Data Management plan
* @EstherPlomp wrote a new subchapter which was recently merged, but it was not added to the table of content.
This PR updates the _toc.yml with the missing subchapter
> Update table of content with the new subchapter on Data Management plan

- book/website/reproducible-research/rdm/rdm-dmp.md
Fixes a stale link to the TU Delft's RDM portal.
Fixes #1727 
* Update a stale link
I believe @EstherPlomp wrote and linked this resource. Could you check if I have linked the correct page?
> BF: Fix stale links to TU Delft's RDM portal

- book/website/reproducible-research/rdm/rdm-checklist.md
Remove unnecessary apostrophe on line 20: "That' is how yours should look" -> "That is how yours should look"
* Remove unnecessary apostrophe on line 20: "That' is how yours should look" -> "That is how yours should look"
> Remove unnecessary apostrophe

- book/website/reproducible-research/vcs/vcs-github.md
Fixes small grammatical error regarding noun determiner.
* Line 9 currently says:
_"In this section, we will discuss how to use Git commands to work with online Git repository."_
* I suggest we can change this to contain an article, or alternatively change the noun form:
_"In this section, we will discuss how to use Git commands to work with an online Git repository."_ or
_"In this section, we will discuss how to use Git commands to work with online Git repositories."_
> Add determiner to "online Git repository"

- CONTRIBUTING.md
Fixes #1755 
* found updated link for inclusive writing guide.
* found different blogpost about creating colour-blind friendly diagrams.
> Update links and Gitter section in contributing guide

- book/website/_toc.yml
- book/website/collaboration/github/github-resources.md
Addresses but does not close #1637.
* capitalisation of subchapter name in toc
* renaming of headings to be more consistent with the rest of the book, and to move heading 'bibliography'
* added label
* used MyST for image
* minor typo removed in final sentence
> Maintaining Consistency in github-resources.md

- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
Fixes #1766 
* Uses the correct link
> Fix link to postBuild section

- book/website/collaboration/new-community/new-community-guide.md
- book/website/collaboration/remote-collab/remote-collab-conferences.md
- book/website/collaboration/remote-collab/remote-collab-participation.md
- book/website/community-handbook/consistency/consistency-language.md
- book/website/community-handbook/coworking/coworking-organisation.md
- book/website/community-handbook/newsletters/newsletters-process.md
Partly addresses #1670
Jupyter warnings..
> Fixing jupyter warning

- book/website/reproducible-research/code-quality/code-quality-style.md
This PR improves the readability of some of the sentences in the coding style section by rephrasing or adding commas.
* Improves grammar in several locations in the coding style page
* Replaces a Google style guide hyperlink that seemed out of place.
> Make several grammar improvements

- book/website/reproducible-research/renv/renv-vm.md
Line 26 reads: "For example, in the 'Why This Is Useful' section of this **chater**". This should be "chapter".
* Update typo
> Update typo: "chater" to "chapter"

- book/website/reproducible-research/renv/renv-containers.md
An external link to a Youtube video on Singularity did not parse into its alt-text, and displayed the full URL instead.
* Shortened link, fixed Markdown syntax so link is parsed correctly.
> Fix hyperlink that did not parse

- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
Fixes the config files link in the Zero to Binder Python lesson.
* Just fixing the link :)
> Fix link in Zero to Binder Python docs

- book/website/collaboration/github/github-contributors.md
Fixes #1635.
* Label headings
* Two grammar improvements
> Update headings to maintain consistency

- book/content/reproducibility/04/barriers.md
Addresses Barrier number 2 in #696.
Added text to the "Publication bias" barrier
> Add barrier 2 (publication bias) to barriers.md in reproducibility chapter

- book/content/reproducibility/04/barriers.md
Addresses Barrier number 3 in #696 
Added text to the "Held to higher standards than others" barrier
> Add barrier 3 (higher standards) to barriers.md in reproducibility chapter

- book/content/reproducibility/04/barriers.md
Brief description of barrier 9 'Being reproducible does not mean the answer is right'.
Addresses Barrier number 9 in #696 
Added text to the "Being reproducible does not mean the answer is right" barrier
> Add barrier 9 (reproducible not right) to barriers.md in reproducibility chapter

- book/content/reproducibility/04/barriers.md
Added two paragraphs, summarising issues with handling big data and barriers to performing reproducible analysis of it.
Addresses (but does not close) #696 
* Paragraph One - Big data overview and issues with data handling.
* Paragraph Two - Big data analysis issues such as high performance computing and seeding.
- @JAEarly
- @georgiatomova
- @swalkoAI
- @giuliaok
> Add barrier 8 (big data) to barriers.md in reproducibility chapter

- book/content/reproducibility/04/barriers.md
Short paragraph on how reproducibility can be a barrier in getting considered for promotion.
Fixes #<NUM>
> Add barrier 4 (considered for promotion) to barriers.md in reproducibility chapter

- book/website/_static/web-analytics.js
Tests #1660 #431
* Creating a new test
* Motomo URL: https://theturingwaynetlify.matomo.cloud/
* User: theturingway@gmail.com
* Ask Malvika for the password by pinging her [on Slack](https://join.slack.com/t/theturingway/shared_invite/zt-fn608gvb-h_ZSpoA29cCdUwR~TIqpBw)
> Preview/test Matomo analytics on this branch

- book/website/collaboration/github/github-readme.md
Fixes #1633
After Proposed changes
Screenshot
> fix: Maintaining Consistency in github-readme

- README.md
Now that gitter has enabled full Matrix integration ([see here for info](https://blog.gitter.im/2020/09/30/gitter-element-acquisition/)) the gitter room also has an "official" matrix address so I've updated the link in the "Get in touch" section.
* Minor update to the Matrix sentence in "Get in touch" section
> Update link to Matrix chat room

- book/website/_config.yml
Adds a primary language attribute to the site. This tells screen readers the main language used to ensure correct pronunciation - see https://web.dev/html-has-lang/?utm_source=lighthouse&utm_medium=devtools for more information.
Instructions on changing sphinx configuration from: https://jupyterbook.org/advanced/advanced.html, Configuring to Improve Accessibility section.
Accessibility expertise from @RobPrecious !
* Added language : en to the sphinx configuration.
> Adding primary language for screen reader accessibility 

- book/website/collaboration/new-community/new-community-differences.md
Appends paragraph on determining level of assumed knowledge between diverse.
* Appends paragraph on determining level of assumed knowledge between diverse.
* General cohesion with the rest of the page
Andrea Luppi @andrealuppi
Cat Saunders @NotActuallyACat
Peter Strong @peterrhysstrong
Chris Tomlinson @tomlincr
- [ X] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file:
> Add Determine Assumed Knowledge Between Diverse Team Members

- book/website/ethical-research/activism/activism-unionisation.md
Fixes a typo in the Activism chapter
> Fix a typo

- communications/GSOD-applications/GSoC-2021.md
* The Turing Way is applying to participate in GSoD 2021
* File with details submitted with INCF has been added
> Create GSoC-2021.md file for initial application

- book/website/collaboration/collaboration.md
- book/website/collaboration/github-collaboration.md
- book/website/collaboration/github/github-roadmapping.md
Fixes #1631, Fixes #1632,  Fixes #1634
> fix: Maintaining Consistency in collaboration.md 

- book/website/reproducible-research/open/open-data.md
- book/website/reproducible-research/rdm/rdm-sharing.md
Fixes #1701 & #895
* Add a Data Availability Statement to the RDM chapter, section 'Data sharing & Archiving'
* Move the information about barriers to Data Sharing to the 'Open Data' section in the 'Open Research' chapter
> Update Data sharing and archiving in the RDM book with a Data Availability Statement section and fix duplication with Open Data section

- book/website/reproducible-research/code-quality.md
Two grammar changes to the section on static code checking.
Two changes:
* "lesser" should be "less" since we mean to modify the amount of time taken;
* "much time" should probably be "much less time", to emphasise that statically checked code may be easier to test.
> Two grammar changes

- book/website/reproducible-research/testing.md
* Add commas for clarity on lines 57 and 59
> Add commas for clarity on lines 57 and 59

- book/website/reproducible-research/compendia.md
The hyperlink on line 159 does not render in Netlify—it shows as plaintext. 
* We can add an alias for it to show it as a link.
> Add hyperlink alias

- book/website/reproducible-research/risk-assess.md
Fixes a few grammar issues.
See diff for details
> Update grammar in risk-assess.md

- book/website/communication/os-comms/os-comms-issue-tracking.md
Fixes #1628 :Maintaining Consistency in os-comms-issue-tracking.md.  Look for reviewer's suggestions. @martinagvilas 
* *Add labels to all headers as recommended in the style guide.*
* *Check for proper grammar and spelling.*
* *All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.*
* *The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: *
> [Review Needed]Add labels and improve grammar in os-comms-issue-tracking.md. 

- book/website/community-handbook/style.md
Add a "tips" section containing to ensure moving forward #1740 and #1670 are avoided. 
* Added "tips" section to offer style guidance for items that triggered previous issues.
* Also fixed two typos in the text.
> Add "tips" section

- workshops/github-workshop/2021-05-13-intro-workshop.md
> Files for GitHub workshop to help folks test PRs

- workshops/github-workshop/2021-05-13-intro-workshop.md
* Adding a file where participants can test their PRs
> Create 2021-05-13-intro-workshop.md for demo and report

- workshops/github-workshop/2021-05-13-intro-workshop.md
Fixes #<NUM>
*Testing PR from Github workshop
> Added my details: María Nanton

- workshops/github-workshop/2021-05-13-intro-workshop.md
- Testing PR from GitHub workshop
> Added my details: Lotty Coupat

- book/website/reproducible-research/rdm/rdm-fair.md
I have added image to the fair principles to complete issue #1884.
- Adding image to fair principles
- Does the code render properly?
- Is this the correct place to put it
- [- ] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: lottycoupat
> Image update rdm-fair.md

- book/website/reproducible-research/overview.md
Re: Issue #1878 
Inserted the figure with @EKaroune 's solution in the pull request #1896
Fixes #<NUM>
*Added image to the Guide's for Reproducible Research Overview. Fixes #1878*
* *Added ResearchCycle image*
> Added image to reproducible research overview

- book/website/reproducible-research/overview/overview-definitions.md
Re: issue #1879
Fixes #<NUM>
*Added image to the Guide's for Reproducible Research Overview. Fixes #1879 *
* *Added reproducibility grid image*
> Add image to Overview

- book/website/reproducible-research/vcs.md
Re: Issue #1882
Fixes #<NUM>
Added image to the Version Control page. Fixes #1882 *
* *Added Version Control image.
> Add version control image

- book/website/reproducible-research/credit.md
Fixes #<NUM>
Current hyperlink to "Open Research" leads to ./open-research, but the actual URL is just ./open.
* Amend hyperlink to correct URL
> Fix "Open Research" link

- book/website/reproducible-research/testing/testing-types.md
Grammar and phrasing can be improved in the Testing Types section.
* Added multiple missing particles and conjunctions. Rephrased a few formulations.
> Make grammar and phrasing changes to Testing Types

- workshops/github-workshop/2021-05-13-intro-workshop.md
Test PR pre-book dash to check if I'm doing it right.
> Late Test PR

- book/website/project-design/project-design.md
> Update a typo in project-design.md

- book/website/reproducible-research/reviewing/reviewing-workflow.md
Adding an image in the Code Reviewing Workflow page. 
Fixes #1891
* Adding an image.
* Deleting table of content.
> Adding ReadableCode image

- book/website/ethical-research/activism/activism-unionisation.md
I added the list of French, Italian and Spanish unions. For France I wasn't able to find one that specifically for science and data science, so I added the largest ones. 
* *Addition of Italian, French and Spanish unions to the list*
- [ x] Everything looks ok?
- [ x] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: <https://github.com/bcamino>
> French, Italian and Spanish unions added

- book/website/reproducible-research/credit.md
Fixes #1888
Fixes #1887 
* Adding 2 illustration in the credit chapter
- Adding 2 illustration in the credit chapter
> Added two images in the credit.md page

- book/website/reproducible-research/ci.md
Adding imagine on Continuous Integration. 
Adding image to fix issue #1889 
Does it render correctly?
Is this the correct place?
- [-] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
> Image Update CI.md

- book/website/reproducible-research/testing/testing-exceptions.md
On lines 94, 97, 102 there are three images being imported to illustrate an example. Indenting the Markdown code that imports the image results in it being treated as a blockquote, which prevents the actual image from showing. 
* Removing the indentation resolves the issue above.
> Remove indentation on image import code

- book/website/_config.yml
Trivial fix, just needs approval and merge.
> Update copyright year

- book/website/reproducible-research/rdm/rdm-metadata.md
The OSF's " How to Make a Data Dictionary " link was broken, fixed it
Fixes broken link on data dictionaries
* *Fixed broken link*
> Fix broken link

- book/website/reproducible-research/reviewing.md
Adding an image in the Code Review page. 
Fixes #1886
* Adding an image.
> Adding BugCatching image

- book/website/reproducible-research/rdm/rdm-storage.md
Adding an image to Data Storage and Organisation
Fixes #1885
* Adding an image.
> Adding VersionControl image to Data Storage

- book/website/community-handbook/consistency/consistency-formatting.md
Removes duplicate example code by replacing it with a link to the style guide.
This makes the page more readable and should be more robust to future changes.
* Replaces code with link
> replace duplicate YouTube demo with link to style guide

- CONTRIBUTING.md
*Minor wording change to fix typo/unclear wording.
Also adds a link to the style guide, which gives further info for the reader.*
> improve wording (borrowed wording from the style guide) and add link to the style guide

- book/website/communication/citable.md
> fix typo that was causing link to break

- book/website/reproducible-research/ci/ci-practices.md
Added imagine for continuous integration best practices to solve issue #1890 
Added image. 
Does it render correctly? 
Is the description accurate?
> Update Image ci-practices .md

- README.md
Fixes #1977 
*Fixes the broken link of team photo in README.md file*
* *Changing the url of teams photo from book/website/figures/TuringWayTeam.jpg to book/website/figures/theturingway-team.jpg in README.md*
> fixed-broken-link-of-team-photo-in-README.md

- workshops/github-workshop/2021-07-05-intro-workshop.md
I added empty name holders for those who hadn't signed up yet (to reduce merge conflict down the road)
Fixes #<NUM>
> Created File for PR Activity

- workshops/github-workshop/2021-07-05-intro-workshop.md
> Added my name and information 

- workshops/github-workshop/2021-07-05-intro-workshop.md
> Adding information to name

- workshops/github-workshop/2021-07-05-intro-workshop.md
> ADD comment by my name

- workshops/github-workshop/2021-07-05-intro-workshop.md
> Add my name to 2021-07-05-intro-workshop.md

- workshops/github-workshop/2021-07-05-intro-workshop.md
> EDIT added info against my name

- workshops/github-workshop/2021-07-05-intro-workshop.md
> ADD info next to name Victoria

- workshops/github-workshop/2021-07-05-intro-workshop.md
> EDIT added info on my line

- workshops/github-workshop/2021-07-05-intro-workshop.md
> EDIT added info to my own name

- .github/workflows/ci.yml
- .github/workflows/lorem-ipsums.yml
- .github/workflows/no-bad-latin.yml
- .github/workflows/test-file-size.yml
- netlify.toml
Duplicate of https://github.com/alan-turing-institute/the-turing-way/pull/2015
Some PRs do not require CI tests to be run, such as those from the all-contributors bot. This PR changes the triggers of our tests to **exclude** branches that match `all-contributors/**` and **includes** pushes to paths that match the `book` directory. This should make **when** our tests run be more efficient. (See commit messages for more context.) The Netlify config file has also been updated to **not** deploy previews for branches that contain `all-contributors`.
Issue is that a lot of our CI tests are required for merging - do we lift these protection rules?
* Added conditional to exclude branch names containing "all-contributors"
* Added positive path pattern matching
* Added ignore pattern for …
> Tweak CI triggers to exclude all-contributors bot

- book/website/project-design/pd-overview/pd-overview-repro.md
- book/website/project-design/project-design.md
* Minor errors in a recently merged chapter
* Fix typos
* Fix minor phrasing errors
> Minor error fixing in the Project Design Overview chapter

- book/website/communication/citable/citable-steps.md
broken image link for DOI image
Fixes #<NUM>
> fixing image link for DOI image

- book/website/ethical-research/activism.md
Addresses (but does not close) #2028
> updates guide name and fixes some links

- book/website/community-handbook/coworking/coworking-collabcafe.md
Updates the hackMD link which was outdated
> Update HackMD link in the collaboration cafe

- book/website/afterword/contributors-record.md
- contributors.md
Updating my contributor record to reflect my current work
> Updating Sarah's contributor record

- book/website/_bibliography/references.bib
- book/website/_toc.yml
- book/website/afterword/glossary.md
- book/website/communication/aa.md
- book/website/communication/aa/equitable.md
- book/website/communication/aa/interdisciplinary-personal-stories.md
- book/website/communication/aa/large-personal-stories.md
- book/website/communication/aa/misconduct.md
- book/website/communication/aa/overview.md
- book/website/communication/aa/resources.md
- book/website/communication/aa/tips.md
- book/website/communication/aa/traditions.md
- book/website/community-handbook/acknowledgement/acknowledgement-members.md
New chapter to discuss academic authorship in academic papers and projects.
Fixes #<NUM>
> Academic authorship chapter for Guide for Communication

- README.md
> Fix incorrect link on readme

- CONTRIBUTING.md
make link more precise to make it easier to check whether there are open pull requests from the allcontributors bot
> make link more precise to make it easier to check whether there are open pull requests from the allcontributors bot

- book/website/reproducible-research/rdm/rdm-data.md
- book/website/reproducible-research/rdm/rdm-dmp.md
updates links of ukdataservice
> Fix ukdataservice links

- workshops/github-workshop/2021-11-03-bookdash-github.md
> Added Alden's name

- book/website/collaboration/github-novice.md
- book/website/collaboration/github-novice/github-novice-advanced.md
- book/website/collaboration/github-novice/github-novice-features.md
- book/website/collaboration/github-novice/github-novice-firststeps.md
- book/website/collaboration/github-novice/github-novice-motivation.md
- book/website/reproducible-research/vcs.md
This PR provides revisions to the collaboration/GitHub-novice chapter.
It may contribute to a few issues, but I didn't see one specifically for chapter revisions.
- adds terms to glossary
- adds links to other chapters/info
- add resources for publishing software that's hosted on GitHub
- fixes typos and other grammar
> GitHub chapter review

- book/website/collaboration/github-novice/github-novice-features.md
- book/website/collaboration/github-novice/github-novice-motivation.md
Updates links, following #2141
> Update internal links in github chapter

- .zenodo.json
* Making released via GitHub to Zenodo picks top contributors rather than allowing us to add authors.
* This PR adds a metadata for the author to be The Turing Way community
* adds a JSON file with one author: The Turing Way community (we might want to update this in the future)
> Create .zenodo.json to add metadata on The Turing Way community as author

- book/website/reproducible-research/renv/renv-containers.md
Assumed to be a typo, couldn't see sensible context for it otherwise.
I couldn't find an open issue or PR for this, and it seemed like a good first PR to raise.
> Deletes a duplicated sentence in Docker section

- book/website/reproducible-research/open/open-data.md
Switching reference formatting from `{cite:t}` to `{cite:ps}` as per the [style guide](https://the-turing-way.netlify.app/community-handbook/style/style-citing.html).
> reference formatting in open data section

- book/website/collaboration/github-novice.md
- book/website/collaboration/maintain-review.md
- book/website/reproducible-research/open/open-access.md
- book/website/reproducible-research/vcs/vcs-github.md
Fixes a number of typos and rewords a sentence for clarity
* Fixed typo under version control/contributing to other projetcs
* Fixed typos under open access publishing
* Fixed typo in github novice/summary
* Fixed typo, unclear wording in collaboration maintain-review/summary
> Fix minor typos and wording changes

- book/website/_bibliography/references.bib
Tidy up bibliography by removing empty doi field
> Tidy up bibliography by removing empty doi field

- .zenodo.json
- CITATION.cff
Add citation.cff file with metadata
> Create CITATION.cff file for The Turing Way

- .zenodo.json
I am fixing this error message:
- "errors": "The license ID you have selected is not present in our system. For the available licenses please check in the following URL https://developers.zenodo.org/#licenses"
by replacing the license entry to:
- cc-by
> Update .zenodo.json because combined license is not recognised

- book/templates/chapter-template/chapter-content/chapter-content.md
- book/website/community-handbook/style.md
This closes #2162. :)
I have built it locally just to be sure before pushing the commits.
* Adds a section to the Style page mentioning syntax highlighting
* Adds syntax highlighting where relevant
> Fix styling markdown chunks: Closes #2162

- .zenodo.json
This PR is updating license from 'cc-by' -> 'cc-by-4.0'
> Update .zenodo.json with license cc-by-4.0

- .zenodo.json
- CITATION.cff
- README.md
- release-workflow.md
* This PR will create a short manual for how to do regular releases via GitHub
* Describe the CITATION.cff file, process to validate it and convert to zenodo.json
* Create a new tag and draft a release on GitHub (possible only by the admins)
> [WIP] Describe process to make regular releases via GitHub

- project_management/impact_statements/patricia_herterich.md
> Fix typo in patricia_herterich.md

- CONTRIBUTING.md
Fixes #2204 
* This PR will add links to Coworking callls
* Adding links to the coworking calls
> Adding Collaboration Cafe link

- book/website/reproducible-research/open/open-hardware.md
- book/website/reproducible-research/overview/overview-resources.md
> fix markdown formatting of nonconsecutive headers

- open-life-science-mentoring/README.md
Fixed grammatical errors in the OLS mentoring readme
Amended some grammatical errors in the text of the OLS mentoring README file. 
* *Grammatical changes.*
> Updated open-life-science-mentoring/README

- ways_of_working.md
Signed-off-by: Achintya Rao <achintya@achintyarao.in>
Adds links to the GitHub handles of all the people mentioned.
> Add GitHub handles with links

- book/website/reproducible-research/code-quality/code-quality-style.md
List of formatting tools lacked an example/recommendation for R.
Fixes #2220.
Adds R / formatR to table in code-quality-style.md
> Added formatR to list of formatter tools

- book/website/reproducible-research/code-reuse.md
- book/website/reproducible-research/code-reuse/code-reuse-details.md
- book/website/reproducible-research/code-reuse/code-reuse-overview.md
Small edits/additions in "Reusable code" section.
- Small edits for more consistency
- Added examples so that concepts like "findable in space and time" and "hardcoded bits" are more relatable.
> small edits/additions in "Reusable code" section

- book/website/_toc.yml
- book/website/collaboration/github-novice.md
Fixing a few minor typos (once seen, cannot be un-seen 😆).
> Github -> GitHub

- book/website/reproducible-research/overview/overview-resources.md
Header is not being processed as expected.
> Fix mark-up

- book/website/afterword/contributors-record.md
- contributors.md
Please update my record!
* Add ORCID: 0000-0002-6850-8375
* Update current role and extra info
> Update Ismael-KG's contributor record

- book/website/community-handbook/coworking/coworking-collabcafe.md
- book/website/community-handbook/coworking/coworking-weekly.md
* Since we will have new members chairing these sessions, I am adding a small checklist describing what chairing involves
* Add checklist
* update where needed
> Add checklist for chairing coworking sessions

- README.md
- book/website/_toc.yml
- book/website/collaboration/new-community.md
- book/website/collaboration/new-community/new-community-teamwork.md
- book/website/project-design/pd-overview/pd-overview-repro.md
Fixes #2207 
- Add a new 'teamwork' section to 'Managing a New Community and Team' chapter
- Add link to teamwork section in 'communication & collaboration' part of project design
> Add teamwork section to 'Managing a New Community and Team' chapter

- project_management/2021-07-ux-funding-turing.md
Partially addresses #2071 
* Adding proposal for a recent grant for _The Turing Way_
* Adding a proposal folder, and UX proposal draft
> Add UX/UI proposal to the project management folder

- book/website/_toc.yml
- book/website/collaboration/research-infrastructure-roles/ram.md
Adding a short section on RAMs to the Open Infrastructure Roles chapter.
> Adding a short section on RAMs

- book/website/project-design/project-design.md
> Proofreading Guide for Project Design

- book/website/reproducible-research/rdm/rdm-metadata.md
* Removing redundant sentences from the metadata subchapter
> Update rdm-metadata.md to remove redundant sentences

- ways_of_working.md
* Minor update as the UX project is concluding related to #2071 
* Move list of members (@myyong, @LydiaFrance and @Iain-S) to the previous member's list  
* Update end month to Jan 2022
* For the conclusion we are waiting for a PR merging the updates made by the team to The Turing Way and an issue sharing the test website that can allow our community members to see thee added features to explore profile based curated chapters
> Update ways_of_working.md to move UX project members under 'previous members' 

- book/website/community-handbook/coworking/coworking-collabcafe.md
Fixes #2268 
* Found and replaced a broken link
TODOs:
> Update coworking-collabcafe.md to fix issue #2268

- book/website/reproducible-research/open.md
* Update alt text that are not descriptive
* Need help curating and updating more images
* Alt text updated for open.md
> Some alt texts in the book needs updating to make them descriptive

- README.md
- ways_of_working.md
Adding Anne's info as a community manager
> Update repo with Anne's info

- book/website/afterword/glossary.md
- book/website/ethical-research/self-reflection/sr-power.md
- Fix typos (hanging parenthesis and missed accent on name)
- Update definition for clarity, drawing on Wikipedia entry
- Remove link (which is the first result on Google (for me) and so which is unlikely to provide additional value
> Update intersectionality entry in glossary

- book/website/reproducible-research/renv/renv-containers.md
updated to reflect that docker can now be run rootless
> docker rootless info

- book/website/_bibliography/references.bib
- book/website/communication/aa.md
- book/website/communication/aa/aa-overview.md
Supercedes, and closes #2103.
Minor wording and adding of references.
> Minor wording tweaks to authorship chapter intro

- book/website/_bibliography/references.bib
Update broken link, as pointed out by user `wwhsiao` oh hypothes.is ([here](https://hyp.is/lDRhTAOOEey-4x-gvZjW3Q/the-turing-way.netlify.com/afterword/bibliography.html))
> Update broken link

- ways_of_working.md
* Adding translation team members and Binder PI 
* Add members
* Check who is missing
> Add binder and translation team

- ways_of_working.md
Related to #2325. Adding Luke and clarifying titles.
- add @lukehare as binder administrator. 
- clarify titles.
> Job title changes

- .github/ISSUE_TEMPLATE/config.yml
- .github/config.yml
- book/website/community-handbook/community-handbook.md
- book/website/community-handbook/coworking/coworking-collabcafe.md
- book/website/community-handbook/templates/template-bookdash-precall.md
- book/website/community-handbook/templates/template-coworking-collabcafe.md
- communications/collaboration-cafe/collaboration-cafe-template.md
- communications/promotion-pack/faqs.md
Closes #2333 (see description and discussion there)
> fix broken collaboration cafe links

- communications/promotion-pack/README.md
* Update team details
* Remove outdated information
* add Anne's name and include link to contributors as well as core team page
> Update team details in the promotion pack's README

- project_management/credit_requests/turing_mybinder_azure_credit_request_template.md
Add explainer that mybinder.org requires diverse funding sources for long-term sustainability
> Update Binder credit request template

- ways_of_working.md
Added Sophia Batchelor to Project Member list.
Added Sophia Batchelor to Project Member list.
> Updated ways_of_working.md

- book/website/reproducible-research/open/open-access.md
* Add this video in the open access chapter: https://www.youtube.com/watch?v=Mycp7SzBWB0&feature=youtu.be
* Update the chapter with the video
* Add a sentence describing what this video is about
> Update open-access.md with Vicky's video on open access

- book/website/reproducible-research/rdm/rdm-sharing.md
*A hyperlink to the Open Data section did not work because a "`" was missing on line 21.
* *Add "`" to fix the hyperlink on line 21
> Update rdm-sharing to fix hyperlink

- book/website/reproducible-research/rdm/rdm-sharing.md
Added scriberia illustration
Added a scriberia illustration for this chapter. 
* Added 'birds of open data' illustration
> Update rdm-sharing.md with illustration 

- book/website/_bibliography/references.bib
- book/website/_toc.yml
- book/website/communication/comms-overview.md
- book/website/communication/communication.md
- book/website/communication/open.md
- book/website/communication/open/education.md
- book/website/communication/open/open-education.md
- book/website/reproducible-research/open/open-scholarship.md
Fixes #2362
Adding more contextual information around Open Education, other than just Open Educational Resources, and moving this Chapter to the Communication guide as this is not necessarily part of reproducible research. 
* Add a chapter on Open Scholarship in the Communication guide to move the information about Open Education/Open Educational Resources there. As a follow up the Open Research chapter should probably be moved under Open Scholarship.
> Add chapter on Open Scholarship and section on Open Education to Communication guide 

- book/website/reproducible-research/renv/renv-containers.md
Fixes #2272
* Update/correct existing Singularity discussion
* Add brief discussion of using GPUs with Singularity
Note that this branch is building on my podman branch.
> Singularity GPU support

- book/website/reproducible-research/open.md
This is a very minor edit, in terms of content, but an important omission in my view. It simply encourages people to look up the Open Definition when introducing the list of "open" concepts.
* Add a note and link to https://opendefinition.org/
> Reference the Open Definition in open.md

- ways_of_working.md
+ minor housekeeping
Added name to project member list and fixed some typos!
Fixes #<NUM>
Name + typos
* Adding name to project member list
- [x ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
> Added name to project members

- book/website/project-design/pd-overview/pd-overview-repro.md
1. Prevent -> prevents
2. Not knowing how does project planning fit -> not knowing how project planning fits
3. That -> arise that
4. Would -> does
5. Inserting you and to
Fixes #<NUM>
> Fixing typos/grammar

- book/website/communication/dif-articles/micro.md
> Fix typo in micro.md

- book/website/reproducible-research/testing/testing-runtime.md
- book/website/reproducible-research/testing/testing-unittest.md
Some code blocks in the Testing section of the Reproducible Research guide were missing indentation.
> Testing section: indentation fixes

- book/website/reproducible-research/vcs/vcs-git-merge.md
> Fix meaning of sentence 41

- book/website/reproducible-research/overview/overview-barriers.md
Fixes typo in the legend of Figure 10, as pointed out by comment
* Replace _your_ with __yourself__
- Is the grammar ok?
> Fix typo in figure legend

- book/website/reproducible-research/vcs/vcs-git-compare.md
Replace "chose" with "choose".
> Fix typo in text

- book/website/reproducible-research/vcs/vcs-git.md
First edit for clarity, second for consistency
* Changes in wording
- Grammar and intent
> Small edits for clarity and consistency

- book/website/reproducible-research/overview/overview-barriers.md
I was translating in the book in Crowdin and I found a typo 
* *I found a typo in file overview-barriers.md.*
> Fix typo while translating in Crowdin

- book/website/_toc.yml
- book/website/community-handbook/bookdash/bookdash-illustrator.md
* Converting comment from the Book Dash planning issue  #2064 from last year on how we work with Scriberia into a chapter
* Adding a new chapter
* Updating toc file
* Linking some relevant docs where TTW images have been used (besides the book)
* Adding an image from the Book Dash Manchester that is linked to the main repo figure folder
> Create bookdash-illustrator chapter in Book Dash chapter

- workshops/github-workshop/2022-08-04-carpentriescon.md
Added doc for introduction for carpentriescon
Fixes #<NUM>
> Create CrapentriesCon collab-party-doc

- workshops/github-workshop/2022-08-04-carpentriescon.md
- Adding numbers to workshop file
> CarpentryCon: Add numbers to workshop file

- workshops/github-workshop/2022-08-04-carpentriescon.md
Added my name to the Crapentries Con GitHub workshop file
* I added my name to the list!
> Updated CarpentriesCon GitHub Workshop

- workshops/github-workshop/2022-08-04-carpentriescon.md
Added my name
* I added my name to the list :)
> Updated CarpentriesCon GitHub Workshop File

- workshops/github-workshop/2022-08-04-carpentriescon.md
**Added name to the Carpentries Con workshop file**
I added my name to the list
> Updated the Carpentries Con MD document

- workshops/github-workshop/2022-08-04-carpentriescon.md
- Sample pull request for CarpentryCon workshop
- Corresponds to slide 48
> CarpentryCon: Sample Pull Request

- book/website/ethical-research/preclinical-research.md
> remove unnecessary comments

- book/website/communication/citable/citable-cite.md
_Corrected wording in "Citing Research Objects"_
> Update citable-cite.md: Citing Research Objects' #2485

- book/website/reproducible-research/reproducible-research.md
#2492 Resolved
Updated number of contributors from over 100 to over 300
> Updated number of contributors

- workshops/github-workshop/2022-08-04-carpentriescon.md
I added my name to the Carpentries Con GitHub Workshop file
I added my name to the Carpentries Con GitHub Workshop file
> Updated CarpentriesCon GitHub Workshop README

- book/website/community-handbook/bookdash/bookdash-after.md
> Change gitter link to the slack workspace

- book/website/reproducible-research/rdm/rdm-fair.md
Added link to the video on FAIR principles
I deleted the line `For a more practical overview` and replaced it with the necessary information + video
* deleted the old information 
* added new information on FAIR principles  + added links to video
> Updated rdm-fair.md

- book/website/reproducible-research/rdm/rdm-personal.md
Included two new resources to the page
Fixes #2491
> Updated resources

- book/website/collaboration/github-novice/github-novice-motivation.md
> fix-spacing-issue

- book/website/communication/communication.md
fixes #2509 
updated to tag issue
> Updated communication.md file for #2509

- book/website/communication/os-comms.md
> Remove line "Conversation as Collaboration"

- book/website/project-design/persona/persona-contributors.md
> Updated gitter link to slack workspace link

- book/website/reproducible-research/rdm/rdm-storage.md
Added resources at the end of the section on backups and storage: [Data Storage and Organisation](https://the-turing-way.netlify.app/reproducible-research/rdm/rdm-storage.html#) subchapter in the [Research Data Management chapter](https://the-turing-way.netlify.app/reproducible-research/rdm.html)
fixes #2546
> Added a resource

- book/website/reproducible-research/rdm/rdm-dmp.md
> Added resource, video on elements of a DMP

- book/website/communication/communication.md
this pull request fixes #2508 
@rootsandberries , @iramosp & @RabeaMue are working on this issue
> clearify wording in introduction

- book/website/ethical-research/ethics-committees.md
Typo in 'Research Ethics Committees Workflows' guide has been fixed
Fixes #2556
> typo fixed #2556

- .all-contributorsrc
Adding a bunch of new contributors with all-contributors all at once seems to confuse the bot - this fixes the `all-contributorsrc` file, adding a new brackets and fixing a few formatting issues.
> fixed all-contributors json file

- book/website/community-handbook/community-handbook.md
Fixes missing opening `[` for text to be hyperlinked.
* Adds the missing `[`
> Fixes hyperlinking Malvika Sharan

- book/website/communication/binder/zero-to-binder.md
- book/website/requirements.txt
Testing the new version of Jupyter Book
> Update Jupyter Book version

- .github/ISSUE_TEMPLATE/give_a_talk.yml
This just adds a warning that these issues can be closed by an automated workflow and that it's ok to reopen them if needed.
What it looks like rendered
> Add a warning about the automated workflow to the end of the talk checklist issue

- book/website/reproducible-research/renv/renv-package.md
I just came across two books on software packaging, which I thought might be nice to include in the Packaging Systems section. 
* Adding links to two books on packaging
> Add links to Packaging Systems section

- book/website/community-handbook/coc.md
> Fix markdown syntax error for email

- book/website/communication/open.md
- book/website/ethical-research/ethics-open-source-governance.md
- book/website/reproducible-research/open.md
> Modify duplicate labels

- book/website/project-design/sdp/pd-sdp-private-learning.md
> typo which breaks reference

- book/website/requirements.txt
Following up on #2313 now that #2307 (update jupyter-book version) is merged.
Partly undoes https://github.com/alan-turing-institute/the-turing-way/commit/4c59b7f6574b69d9f22ca88b21e4f83cb924d9d0
> Remove redundant dependencies

- ways_of_working.md
This adds me as a project member in the ways-of-working.md
It's one line, so it should be straight-forward to review, but do look out for typos I guess!
> added name to project members in ways-of-working.md

- book/website/reproducible-research/binderhub.md
A mistake in table formatting (extra column on a single line) meant that it was not rendering correctly
The table was not rendering correctly due to an error in formatting
* single line change to fix formatting of the pre-requisites table
*
> Formatting mistake in binderhub.md

- book/website/ethical-research/activism/activism-unionisation.md
Fixes  #2634
Add the most important labour unions in The Netherlands to Guide for Ethical Research/Activism for Researchers/Unionisation
> Add The Netherlands to activism-unionisation.md

- book/website/afterword/glossary.md
> BUG: fix glossary build warning

- book/website/afterword/contributors-record.md
Fixes #<NUM>
* *VU Amsterdam is added with description.*
* *Lena Karvovskaya and Elisa Rodenburg should be under it.*
-->
> Added VU Amsterdam as contributor

- book/website/reproducible-research/renv/renv-containers.md
Fixes #2639
Fix a build warning about highlighting of bash shell code blocks.
* Correct an example command
* Change shell code blocks highlighting from `bash` to `console`
> Fix bash shell lexing problem

- book/website/project-design/sdp/types.md
- book/website/project-design/sdpm/informed.md
Contributes to #2611 
Some top level headers in the project design guide were not 'level 1'.
* Ensure top level headers are the correct level
* Remove trailing whitespace
> Correct top header levels in project design guide

- book/website/community-handbook/style/style-figures.md
... for the example of an alt image text showing when the actual image cannot be shown
_This is a re-do of #2312 (starting fresh because there were some complex commits in there as hotfixes that are no longer necessary)_
> Adding an alt image text

- book/website/community-handbook/templates/template-coworking-weekly.md
> Removal of duplicate "schedule" heading

- book/website/_toc.yml
Rearranges licensing chapters and adds ML pages to TOC
* Move Data Licenses Upin TOC
* Add ML Licenses and ML Case Studies pages to TOC
> add ml license to TOC

- book/website/communication/peer-review/peer-review-overview.md
Fixes #2673
* Fixing broken link to collaboration guide in peer review overview chapter
> fixing collaboration broken link

- README-translated/README-French.md
Addresses but does not close #2107.
*Updating and upgrading the French translation of the ReadMe file.*
* *Typo.*
* *Broken syntax.*
* *Better translation.*
* *Missing text from the English file.*
> 📝Fix typo and outdated labels on the French translation

- book/website/reproducible-research/open/open-access.md
Fixes #2742 
* Removed broken link on video on APCs as has been taken down on YouTube
> removing APC video link in open access chapter as no longer available

- .github/workflows/close-talk-issues.yml
This workflow fails if no open, matching issues are returned by the API and the `all_issues` variable is a type `None`. (See: https://github.com/alan-turing-institute/the-turing-way/actions/runs/3309120079/jobs/5465013028) This PR catches that case and cleanly exits the code
> Cleanly exit the script if no matching issues are found

- book/website/collaboration/research-infrastructure-roles.md
Part of #2684 and #2685 - we are proposing to live update the list of example role titles in the landing for the Research Infrastructure Roles chapter. This will be facilitated by soliciting additional suggestions from the participants in the Big Team Science _Turing Way_ hackathon on Thurs 27 October 2022. 
* Adding an expanded list of RIR titles from audience input
> [Big Team Science Hackathon] Adding to the Research Infrastructure Roles list of job titles

- book/website/collaboration/research-infrastructure-roles.md
- Add additional roles from BTSCON
> adding final BTSCON roles + casing consistency

- .github/ISSUE_TEMPLATE/BOOK_DASH_CHECKLIST.md
- .github/ISSUE_TEMPLATE/FIRESIDE_CHAT_CHECKLIST.md
* This issue creates templates for Book Dash and Fireside Chat planning checklists
* Current book dash planning committee
* Current and previous Fireside chat hosts
---
> Create issue templates for regular events

- book/website/communication/peer-review/peer-review-guidance.md
- book/website/communication/peer-review/peer-review-resources.md
> Add peer review info

- .github/workflows/close-talk-issues.yml
In the Close Talk Issues workflow, handle cases where `talk_date` cannot be extracted from the issue body, causing errors such as:
https://github.com/alan-turing-institute/the-turing-way/actions/runs/3406596179/jobs/5665400691#step:4:136
> [CI] Handle cases where talk_date cannot be extracted from the issue body

- book/website/project-design/sdpm/data-privacy-strategies.md
- book/website/project-design/sdpm/resources.md
- book/website/reproducible-research/rdm/rdm-personal.md
Fixes #<NUM>
PR deleting some of the information in the RDM chapter which is now in the [Managing Sensitive Data Chapter](https://the-turing-way.netlify.app/project-design/sdpm.html)
* Delete information from the RDM chapter
* Add a couple of the resources that were added before the move
> Delete duplicate info from managing senstive data

- book/website/communication/podcasts.md
> Updated recommended podcasts

- book/website/project-design/sdp.md
I added a cross reference to the confidential data section on line 26. 
This fixes #2692
> Added cross reference to Confidential Data

- book/website/ethical-research/ethics-intro.md
Changed definition to defining
Fixes #2780
> Fixed typo line 55

- book/website/community-handbook/templates/template-coworking-collabcafe.md
#2501 We removed an extra + under "Sign up Below"
Fixes #2501
Fixes #2501 
* deleted the +
* that's it.
> Removed extra +

- book/website/ethical-research/ethics-intro.md
- Fixed typo on line 114: replaced IA with AI
Fixes #2782
> Fixed typo

- book/website/ethical-research/ethics-intro.md
- Fixed incorrect citation on line 121
This Pull Request fixed issue #2778
> Fixed typo in citation

- .gitignore
- book/website/project-design/pd-overview/pd-overview-sharing.md
Contributes to (but does not close) https://github.com/alan-turing-institute/the-turing-way/issues/2760.  Specifically, does not address:
- modify opening paragraph - FAIR principles are considered throughout project life
- review full page for tweaks to reinforce message in opening paragraph
-  fixed: inoperable->interoperable typo
- added python virtual environments to `.gitignore`
> Fix typo: project-design/pd-overview/pd-overview-sharing

- book/website/reproducible-research/reviewing/reviewing-recommend.md
closes #2766 
Fixed the broken link in the chapter '[Recommendations and Best Practices](https://the-turing-way.netlify.app/reproducible-research/reviewing/reviewing-recommend.html)', as a part of the Turing November 2022 Book Dash event.
> Corrected link

- book/README.md
Fixes #2670 (workaround)
Update instructions for building the book using a virtual environment.
* Suggest creating a virtual environment in the repos root directory to avoid #2670 
* Update docs to suggest using the built-in Python venv module rather than virtualenv
> Update virtual environment build instructions

- book/website/ethical-research/ethics-open-source-governance.md
Fixes #2642 
Well... partially. There is still some debate about whether the chapter structure should be revised at all, but I've made a start on adding resources. 
* Added list of resources on open source governance
> Adding in additional resources for OS governance on the Ethical Considerations for Open Source chapter

- book/website/project-design/sdpm/data-privacy-strategies.md
This PR adds some suggestions for software to delete personal data.
> add software to delete personal data

- book/website/project-design/sdp.md
> Add a link to cross-reference the subchapter on Metadata

- book/website/community-handbook/templates/template-coworking-collabcafe.md
This addresses issue #2504
Fixes issue #2504 
Added the cake and tea emojis
> Changed the cake emoji

- book/website/communication/citable/citable-steps.md
fixed issue #2554 by adding link to video on line 30.
* added link
- [ x] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/main/README.md#contributors) in the README file.
> updated video link on line 30

- book/website/project-design/sdpm/data-privacy-strategies.md
fixes some lost resources by delayed merging of other PRs
> add anonimisation resources from another PR into managing sdp

- book/website/community-handbook/presenting.md
This reverts commit 3aa8233c2f687679a4cf97c3cf4772fada0d5a26.
Contributes to #2611 #2838
Reverts a commit which undid @da5nsy's fixes
* Revert 3aa8233c2f687679a4cf97c3cf4772fada0d5a26
> Revert "fixing a whoopsie"

- book/website/_toc.yml
- book/website/afterword/glossary.md
- book/website/project-design/sdpw.md
Fix link in TOC (Fixes #2833)
Add links to ancestor page
Add terms to glossary
> Updates to private learning chapter

- book/website/reproducible-research/open.md
> correct alt-text according to issue #2630

- book/website/reproducible-research/open.md
`:` not allowed in alt-text
---
#2611 
#2838
> minor follow up to #2830

- .github/workflows/ci.yml
Implements #2838 
It might also be worth considering the `--keep-going` flag. I'm not including it here because:
- hopefully once this is implemented there will only be one error at a time
- it means that it will fail quicker, so people get feedback quicker, and also less compute time
- If this _doesn't work_ there's less things for us to debug right now (and we can consider adding it in later)
docs reference: https://jupyterbook.org/en/stable/basics/build.html#debug-your-books-build-process
I believe everyone is already in contributors, but for the record: thanks to @sgibson91, @bsipocz, @choldgraf and others for input
> Add continuous integration so that build fails on jupyter-book warnings

- book/website/project-design/sdp.md
> Add final link to SDP intro page

- book/website/project-design/sdpm/resources.md
fix broken link in `project-design/sdpm/resources.md`
#2611, blocking #2838
> fix broken link in `project-design/sdpm/resources.md`

- ways_of_working.md
Fixes #<NUM>
*not sure if there is an issue.*
* *Added my name.*
* *Added VU Amsterdam as my institution.*
> Added name and info

- book/website/project-design/sdp/personal.md
Added a few notes on the direct and indirect identifiers, and the guidelines provided by different government actors on working with sensitive data. Also added links to the subchapter.
> Updated section on personal data

- book/website/project-design/sdp/personal.md
Build gives this warning:
`website\project-design\sdp\personal.md:12: WARNING: Non-consecutive header level increase; 2 to 5 [myst.header]`
which will break future builds (since #2838 / #2861)
Linking back to #2810
I changed the header levels
> fix nonconsecuitive headers on `project-design/sdp/personal`

- book/website/reproducible-research/ci/ci-options.md
This is part of the edition process @BatoolMM and I work on. This PR is very basic, as it's limited to some language/reorder/link edits. 
The new github actions subchapter can either be pushed to this later, or be added as a new PR.  Once it's done, we should consider removing the travis example altogether as their support policy of open source has changed recently.
> CI services chapter

- book/website/project-design/sdp/types.md
Testing to see if the video embeds properly
Fixes #<NUM>
Added script for embedding a video from youtube
> Embedding video link into sensitive data overview intro

- book/website/project-design/sdp/types.md
Addresses issue #2869  
Added a few notes on the different levels of data sensitivity and classification of sensitive data.
> Update on the chapter on types of sensitive data

- Vagrantfile
- book/website/reproducible-research/renv/renv-virtualmachine.md
Fixes #2632
Add section on Vagrant to the reproducible environment virtual machine page.
* Add discussion on Vagrant for portable, reproducible virtual machines
> Add Vagrant section

- book/website/reproducible-research/rdm/rdm-checklist.md
*Fix the internal links in the checklist
> fix internal references RDM checklist

- book/website/project-design/sdp/personal.md
> Fix reference, per #2832

- book/website/_bibliography/references.bib
- book/website/_toc.yml
- book/website/ethical-research/activism.md
- book/website/ethical-research/activism/activism-cultural-change.md
Adding Cultural Change as a sub-section to Research Activism
Fixes #2475
* Add cultural change to the Research Activism summary
* Add a new section on cultural change to the book.
Comment from Anne: Kirstie wrote a document before she went on leave about 'Emergence as The Turing Way's strategy', which is on a HackMD here: https://hackmd.io/@KirstieJane/rJ0jRCaEc
> Add cultural change

- book/website/project-design/project-repo/project-repo-roadmapping.md
Just noticed a broken link for GitHub project boards [on this page](https://the-turing-way.netlify.app/project-design/project-repo/project-repo-roadmapping.html) and replaced it with one that seemed appropriate
Fixes #2881
* Replaced [this link](https://help.github.com/en/articles/tracking-the-progress-of-your-work-with-project-boards) with [this one](https://docs.github.com/en/github-ae@latest/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards)
> Fixed broken link

- book/website/project-design/sdpm/data-privacy-strategies.md
- book/website/project-design/sdpm/informed.md
- book/website/project-design/sdpm/resources.md
Fixes #2884 
- As discussed in Issue #2884, I added the [Data Privacy Handbook](https://utrechtuniversity.github.io/dataprivacyhandbook) as a resource to the Resources subchapter of Managing Sensitive Data Projects.
- I also proposed some minor tweaks to two other subchapters in Managing Sensitive Data Projects.
- Add Data Privacy Handbook to `project-design/sdpm/resources.md`
- Add more GDPR-like language to the `project-design/sdpm/informed.md` subchapter. The GDPR has some more specific requirements which are now a bit clearer.
- In the `project-design/sdpm/data-privacy-strategies.md`:
- Removed the part that said "while limiting the loss of information": you always lose information when anonymising data
- Expanded the Access permissions part and the part on Data transfer
> [Ready for review] Minor tweaks to Sensitive data chapters

- book/website/reproducible-research/code-quality/code-quality-style.md
Thought of a couple of improvements when reading the Code Style and Formatting page of the Turing Way book.
* Remove the mention of Atom in the list of text editors as it has been [sunsetted](https://github.blog/2022-06-08-sunsetting-atom/).
* add a mention to [MISS_HIT](https://florianschanda.github.io/miss_hit/) in the list of code formatters for MATLAB/Octave.
> Suggestions for the Code Style and Formatting page

- ways_of_working.md
Adding @Davsarper to Ways of Working document
> Adding David to Ways of Working

- ways_of_working.md
Updating David's name in the Ways of Working doc - had added incorrectly the first time!
> Updating David's name!

- book/website/communication/research-objects.md
Fixes minor formatting errors.
> Minor error update in the chapter research objects

- contributors.md
Partially addresses #2723
* Add the bio provided by the participants
* Add bio (Orcid, participation details etc.)
* Ask participants' who have not provided details to directly edit on this PR
* Merge this before Friday, 17 Dec
> Update contributors.md with info from the Book Dash Nov attendees

- ways_of_working.md
- Adding @s-laher to Ways of Working document
> Adding Shakir to WoW doc

- book/website/project-design/project-repo/project-repo-advanced.md
> add missing space

- README.md
- Editing "Team" section of README.md document
> [WIP] Adds link to Ways of working document to README.md

- book/website/collaboration/github-novice/github-novice-features.md
- book/website/collaboration/github-novice/github-novice-firststeps.md
- book/website/reproducible-research/licensing/licensing-checklist.md
Removes a link that was autogenerated, but presumably was unintended
> Remove (presumably) unintended links to the websites `readme.md` and `license.md`

- book/website/community-handbook/style/style-figures.md
Updating the style guide for images
* Corrects some errors in the style guide for images
* Adds a paragraph additionally on Alt text
* Improves alt text examples
> Add alt texts properly in the style guide

- book/website/collaboration/research-infrastructure-roles.md
* Preparing for a talk, and wanted to point to this chapter -- although I would like to propose a minor update to improve the definition of RI roles
* A sentence update
> Update research-infrastructure-roles.md to make sure we don't categorise them as 'support'

- ways_of_working.md
I've added myself as the Research Project Manager
> I added myself to the team

- book/website/ethical-research/activism/activism-unionisation.md
Fixes #2960 
Adds @yabellini recommendations for unions in Lat Am + UTAW info + some formatting updates
* Argentinian unions added
* UTAW added for UK
* Updated some formatting
> Update unions page with more recommendations

- ways_of_working.md
Adding myself as discussed today with @aleesteele
> adding mself to ways of working

- .github/ISSUE_TEMPLATE/BOOK_DASH_CHECKLIST.md
- .github/ISSUE_TEMPLATE/FIRESIDE_CHAT_CHECKLIST.md
- book/website/_toc.yml
- book/website/community-handbook/fireside-chat.md
- book/website/community-handbook/fireside-chat/fireside-chat-checklist.md
- book/website/community-handbook/fireside-chat/fireside-chat-roles.md
* Adds two subchapters, one with planning checklist, and other with the roles and responsibilities
* Planning checklist issue template is linked to the landing page
* two subchapters with planning checklist and roles and responsibilities
> Add checklist and responsibility document for Fireside chat

- book/website/community-handbook/fireside-chat.md
- book/website/community-handbook/fireside-chat/fireside-chat-checklist.md
connected to #2985 
* I have merged the initial edits to the Fireside Chat, this PR edits minor errors
* Editing fireside chat chapters
> Update fireside chat chapters - editing/review

- ways_of_working.md
> add chris to list of contributors

- .zenodo.json
- CITATION.cff
- release-workflow.md
* Pushing changes in the files for new release
* Updated CITATION.cff and .zenodo.json file using the release workflw
* the workflow guide has a missing step that is added in this PR
> Updated files for new release and update release-workflow.md to add a missing step

- CONTRIBUTING.md
- book/website/reproducible-research/ci/ci-resources.md
- book/website/reproducible-research/make.md
- book/website/reproducible-research/renv/renv-yaml.md
> MAINT: remove mentions of travis

- tests/pull_files.py
> MAINT: adding raise_for_status

- netlify.toml
Create redirects for https://the-turing-way.netlify.app/welcome.html so it lands in https://the-turing-way.netlify.app/index.html
> Add a redirect to welcome.html

- book/website/collaboration/collaboration.md
- book/website/collaboration/coworking.md
- book/website/collaboration/github-novice/github-novice-firststeps.md
- book/website/collaboration/github-novice/github-novice-motivation.md
- book/website/collaboration/maintain-review/maintain-review-review.md
- book/website/collaboration/organising-conference.md
- book/website/collaboration/organising-meetings.md
- book/website/communication/aa/aa-equitable.md
- book/website/communication/aa/aa-misconduct.md
- book/website/communication/aa/aa-overview.md
- book/website/communication/aa/aa-tips.md
- book/website/communication/binder/zero-to-binder.md
- book/website/communication/citable/citable-steps.md
- book/website/communication/dif-articles/methods.md
- book/website/communication/dif-articles/micro.md
- book/website/communication/dif-articles/software.md
- book/website/communication/open.md
- book/website/communication/os-comms/os-comms-channels.md
- book/website/communication/os-comms/os-comms-issue-tracking.md
- book/website/community-handbook/style.md
- book/website/project-design/pd-overview/pd-overview-version.md
- book/website/project-design/sdp.md
- book/website/project-design/sdp/types.md
- book/website/reproducible-research/ci.md
- book/website/reproducible-research/code-reuse/code-reuse-details.md
- book/website/reproducible-research/rdm/rdm-data-curation.md
- book/website/reproducible-research/rdm/rdm-toolkits.md
- book/website/reproducible-research/reviewing/reviewing-checklist.md
- book/website/reproducible-research/reviewing/reviewing-motivation.md
- book/website/reproducible-research/testing/testing-integrationtest.md
Whilst giving the book a complete read through I've caught an assortment of minor errors typos, syntax, grammar, broken links. 
(This is a work in progress as I've not finished my complete read through but I saw a bunch of good first issue go up after the github intro and wanted to get ahead of any duplicated work.)
Each fix is in a separate commit with a descriptive message.
> [Ready for review] Miscalaneous typos, grammatical errors, etcetera

- book/website/reproducible-research/open/open-resources.md
- book/website/reproducible-research/rdm/rdm-personal.md
- book/website/reproducible-research/rdm/rdm-resources.md
- book/website/reproducible-research/rdm/rdm-storage.md
Duplicate information in the personal data which was previously removed but appears to be added back in. 
Fixes #<NUM>
- also added some bulk renaming tools to the data organisation section
- added the resources the Utrecht University RDM team is sharing to the resources :)
> RDM/Open Data: Remove double information

- book/website/project-design/pd-overview/pd-overview-planning.md
Fixes #1836 
This is the start of a review of project design guide led by the TPS Programme Management Team but we welcome contributions and feedback from anyone who has ever planned a project! 
* Add a checklist for project planning 
* Revise text to include more considerations around project planning 
* Add extra links to revised sections or new sections of the book 
* Crossreference with the new chapter on Stakeholder engagement https://github.com/alan-turing-institute/the-turing-way/issues/3105
> [WIP] Update pd-overview-planning.md

- book/website/communication/citable/citable-steps.md
Review this document to add details about making hardware citable.
Fixes #<NUM>
> [WIP] Update citable-steps.md (including hardware)

- book/website/_bibliography/references.bib
- book/website/collaboration/academic-industry/academic-industry-establish.md
Quick suggested change to fit formatting recommended in https://the-turing-way.netlify.app/community-handbook/style/style-citing.html
> Update name of Turing-Roche DSG event in reference file

- .github/workflows/ci.yml
- .github/workflows/external_link_check.yml
- book/website/communication/comms-overview/comms-overview-resources.md
- lychee.toml
Related to #2947 
Changing how link checking works
- upon PR?
- Open a weekly (?) issue using a cron job?
> Restructure link checking

- .github/ISSUE_TEMPLATE/new_chapter.yml
- book/website/_toc.yml
Fixes YAML linting errors on main
* Fix linting errors in toc
* Fix linting errors in new chapter issue template
> Fix YAML linting errors

- .github/workflows/external_link_check.yml
- .github/workflows/resources/external_link_check_header.md
Adds explanatory text to the top of the automated broken links issue. Based on a discussion with @EstherPlomp.
> Improve broken links issue

- .github/workflows/yamllint.yaml
Fixes #3180 
* Ensure yaml lint workflow runs on PRs which modify yaml files
> Run yaml lint workflow on PR

- book/website/community-handbook/presenting.md
Adding a tag so this can be cross referenced
> Add a tag in presenting about The Turing Way chapter

- book/website/afterword/glossary.md
changed to the official definition by oshwa
> Update glossary.md -open hardware

- README.md
Came here to remove a "." that seemed too much. Yes, so very nerdy of me :)
Then I found a broken image link towards the bottom of README that I tried to fix.
The broken link could be a regression from #2950.
If this link fix is good, then some of the README translations may require the same fix. See [here](https://github.com/search?q=repo%3Aalan-turing-institute%2Fthe-turing-way+%22figures%2Fevolution-open-research.jpg%22&type=code).
* updates to `README.md`
> [docs] Minor fixes to README

- governance/community-calls/20230605-coworking.md
- governance/community-calls/20230612-coworking.md
- governance/core-team/meeting-notes/20230609-core-team.md
Will close #3200 
Adds notes from two coworking calls in june (5 & 12 june) and core team meeting (9 june)
- What do we think of this file structure? (especially for the coworking calls)
- Are there any other initial notes missing from this collection? (i.e. collaboration cafe)
- Anything else missing from this PR?
> creating governance folder + adding coworking & core team notes

- book/website/project-design/pd-overview/pd-overview-sharing.md
> [WIP] Update pd-overview-sharing.md -openhardware

- book/website/project-design/pd-overview/pd-overview-sharing.md
@jcolomb I should have suggested these changes before approval - can you check and see if this makes sense.
> Slight update of pd-overview-sharing.md

- .github/workflows/accessibility-alt-text-bot.yml
Fixes #3207
New accessibility bot for alt text automated reminders.
- New workflow added.
> workflows: add accessibility alt-text bot.

- book/website/reproducible-research/rdm/rdm-sharing.md
> Fix minor typo on rdm-sharing.md

- governance/community-calls/20230605-coworking.md
- governance/community-calls/20230619-coworking.md
- governance/community-calls/20230626-coworking.md
- governance/community-calls/20230703-coworking.md
- governance/community-calls/20230710-coworking.md
- governance/community-calls/20230717-coworking.md
- governance/community-calls/20230724-coworking.md
- Adding notes from 19 June 2023 & 26 June 2023
> archiving notes

- .vscode/settings.json
- book/website/communication/os-comms.md
- book/website/community-handbook/coworking/coworking-motivation.md
- book/website/ethical-research/law-policy.md
- book/website/ethical-research/preclinical-research.md
- book/website/project-design/filenaming.md
- book/website/reproducible-research/binderhub.md
- book/website/reproducible-research/case-studies.md
- book/website/reproducible-research/ci.md
- book/website/reproducible-research/licensing.md
- book/website/reproducible-research/rdm.md
- book/website/reproducible-research/renv.md
- book/website/reproducible-research/testing.md
- book/website/reproducible-research/testing/testing-resources.md
Updates chapter landing pages.
Fixes #1663
- update chapter landing pages.
The following pages no longer exist as mentioned in the [issue](https://github.com/alan-turing-institute/the-turing-way/issues/1663):
- [Credit for Reproducible Research](https://the-turing-way.netlify.app/reproducible-research/credit.html)
- [Collaborating on GitHub/GitLab](https://the-turing-way.netlify.app/collaboration/github-collaboration.html)
> book: update chapter landing pages.

- netlify.toml
Netlify builds were failing due to an incorrect publish dir.
It appeared that the base dir and publish dir in `netlify.toml` were being concatenated.
This is an attempt to fix that.
> Adjust netlify paths

- ways_of_working.md
This PR is to add Melissa to Ways of Working document
> Adding Melissa to Ways of Working

- .github/workflows/external_link_check.yml
- book/website/community-handbook/infrastructure/infrastructure-external-link-check.md
Some grammar, spelling, readability improvements for the external link check page.
> Improve external link check page grammar

- book/website/community-handbook/translation/translation-getting-started.md
Fix small typo and missing pronouns.
> Fix typo on the translation-getting-started page

- book/website/collaboration/inclusive-events.md
The landing page had formatting issues which needed to be fixed and brought inline with TTW's Style guide. 
* Added new lines for each new sentence
* Removed whitespace after headings
> Inclusive Events Chapter Landing Page: Fixed Formating

- book/website/communication/peer-review/peer-review-open.md
adding new link to open review sub chapter
> adding PCI link to open review sub chapter

- book/website/_toc.yml
- book/website/reproducible-research/rdm/rdm-find.md
Adding finding data subchapter to RDM chapter in guide for reproducibility.
Issue #3360 
Fixes #<NUM>
> Finding data

- book/website/collaboration/research-infrastructure-roles/data-steward.md
Adding figure and alt-text to the "Data Stewards" page. Fixes #3375.
> [Ready for merge] Updating "Data Stewards" page with figure

- book/website/project-design/data-governance/bigcode_casestudy.md
typos and tweaks for the BigCode Case Study page
Address some typos that made it in to the page and in the process, make some other small tweaks
* Fix typos
> Update typos and tweaks for bigcode_casestudy.md

- book/website/reproducible-research/ci.md
- book/website/reproducible-research/code-quality.md
- book/website/reproducible-research/make.md
- book/website/reproducible-research/renv.md
- book/website/reproducible-research/testing.md
- book/website/reproducible-research/vcs.md
Because we are after June, I wanted to see if I could resolve #3164. This issue should fix #3164.
> [Ready for review] Updating references to Programming Historian

- book/website/ethical-research/ethics-committees.md
> adding ethics-committee-with-text image

- book/website/community-handbook/style.md
Adding an explanation and an example of using bullet points.
Fixes #3398.
* Added a subsection in the style guide for navigating multiple sentences inside bullet points.
* Added an example using Dr Seuss quotes (to stick with the page's theme).
> [ready for review] Add formatting of bullet points to style guide

- book/website/collaboration/research-infrastructure-roles/community-manager.md
Adding image for Research Community Managers. Fixes #3343.
> [Ready for merge] Adding figure and alt-text

- book/website/reproducible-research/rdm/rdm-dmp.md
*[FAIR Wizard](https://fair-wizard.com) is also a DMP tool.*
* *Added FAIR Wizard to DMP tools*
> Added FAIR Wizard to DMP tools

- book/website/ethical-research/activism/activism-cultural-change.md
Add one of the older images to the [cultural change section](https://the-turing-way.netlify.app/ethical-research/activism/activism-cultural-change.html)
partially addresses #3331
> Add image to cultural change

- book/website/_bibliography/references.bib
- book/website/communication/open/education.md
I didn't open an issue because it is just a super small add of a couple of resources to the Open Education section. 
Please check if everything works!
> Add new resources to Open Education

- .github/workflows/crowdin-contributors.yml
Fixes #3419
The workflow wants to commit and push a change then open a PR, so it will need write access to contents as well as for PRs.
* Added `contents: write` permission to GitHub Token in crowdin contributor workflow so it can makes changes to the repo
> Add contents: write permission for crowdin workflow

- book/website/ethical-research/activism/activism-env-impact.md
> [Ready for review] Removes duplicated images

- book/website/afterword/glossary.md
- book/website/collaboration/inclusive-events/inclusive-events-schedules.md
This PR is for adding the Schedule, Agenda, and Programme subsection to the Inclusive Events chapter.
This subsection is about what to consider when create a schedule for an event attended by people with lived experience. There is guidance on session timings, session duration, session formats, what to include in a session description, how to create engagement pathways for participatory sessions/events, and why you should include a person with lived experience in your speaker list. 
Once reviewed, this section will be merged into the [WIP-Inclusive-Events-chapter-Content](https://github.com/the-turing-way/the …
> WIP Inclusive Events Schedule and Agenda Subsection

- book/website/_bibliography/references.bib
- book/website/collaboration/inclusive-events/inclusive-events-tech.md
This PR is for adding the Technology Consideration subsection to the Inclusive Events chapter.
This subsection is about what considerations and implementations need to be made from a technology standpoint in order for an event to be inclusive of people with lived experience. 
It also makes a point about how hybrid events will be naturally more accessible to attendees with lived experience.
Once reviewed, this section will be merged into the [WIP-Inclusive-Events-chapter-Content](https://github.com/the-turing-way/the-turing-way/tree/WIP-Inclusive-Events-chapter-Content) branch. Please refer to Issue #3307 …
> WIP Inclusive Events Technology Considerations Subsection 

- book/website/collaboration/inclusive-events/inclusive-events-comms.md
This PR is for adding the **third** content subsection to the Inclusive Events chapter.
This subsection is about considerations for creating a communications strategy, and how to support your event communications being inclusive of people with lived experience.
Once reviewed, this section will be merged into the [WIP-Inclusive-Events-chapter-Content](https://github.com/the-turing-way/the-turing-way/tree/WIP-Inclusive-Events-chapter-Content) branch. Please refer to Issue #3307 for more information about this chapter.
**Second Review**
- Moved key information checklist 
- Gave dress code and sickness policy …
> WIP Inclusive Events Communications Subsection

- book/website/collaboration/inclusive-events/inclusive-events-location.md
This PR is for adding the **second** content subsection to the Inclusive Events chapter.
This subsection is about considerations for choosing and setting up a venue.  
Once reviewed, this section will be merged into the [WIP-Inclusive-Events-chapter-Content](https://github.com/the-turing-way/the-turing-way/tree/WIP-Inclusive-Events-chapter-Content) branch. Please refer to Issue #3307 for more information about this chapter.
> WIP Inclusive Events Location subsection

- book/website/_bibliography/references.bib
- book/website/collaboration/inclusive-events/inclusive-events-planning.md
This PR is for adding the first content subsection to the Inclusive Events chapter.
Once reviewed, this section will be merged into the [WIP-Inclusive-Events-chapter-Content](https://github.com/the-turing-way/the-turing-way/tree/WIP-Inclusive-Events-chapter-Content) branch. Please refer to Issue #3307 for more information about this chapter.
* Added first draft of Planning and Logistical subsection to the Inclusive events chapter.
> WIP Inclusive Planning and Logistics subsection

- .github/ISSUE_TEMPLATE/give_a_talk.yml
- .github/config.yml
- .github/workflows/close-talk-issues.yml
- .github/workflows/crowdin-contributors.yml
- .github/workflows/release-workflow.yml
Fixes #3470 
* Replace GitHub emoji codes (like `:tada:`) with unicode characters
> Replace emojicodes with emoji in GitHub YAML files

- book/website/collaboration/inclusive-events/inclusive-events-content-guide.md
This PR is for adding the **seventh** content subsection to the Inclusive Events chapter.
This subsection contains recommendations and guidance on content accessibility (e.g. presentations, flyers, and the event website).
Once reviewed, this section will be merged into the [WIP-Inclusive-Events-chapter-Content](https://github.com/the-turing-way/the-turing-way/tree/WIP-Inclusive-Events-chapter-Content) branch. Please refer to Issue #3307 for more information about this chapter.
* Added first draft of Content Accessibility subsection to the Inclusive events chapter. 
* Added cross-referencing headings
Please …
> WIP Inclusive Events Content Accessibility Subsection

- book/website/collaboration/inclusive-events/inclusive-events-resources.md
This PR merges a draft of the Resources page for the Inclusive Events chapter discussed in #3307 into a WIP branch of the chapter. 
* Added resources 
* Organized resources into sections
A review should focus on what a "first draft" of this content should look like
> Adding Resources list to Inclusive Events Chapter

- governance/community-calls/20240108-coworking.md
No open issue, this is a standing meeting.
* Notes from core team co-working on 8 January
> Notes from core team co-working call on 8 January 2024

- governance/community-calls/20240115-coworking.md
No open issue.
Archiving notes from Monday morning co-working on 15 Jan 2024
* Notes added
> Co working notes 20240115

- contributors.md
Related to #3322 
* Add new bios (like for @kallewesterling from a recent Book Dash)
* Update bios where needed (like for @bsipocz)
* Update contributors.md file
> [READY TO MERGE] Update contributors.md with Brigitta and Kalle's Info

- governance/community-calls/20240122-coworking.md
No open issue
* Notes from coworking call on Monday 22 Jan
> Notes from coworking call on Monday 22 January

- book/website/community-handbook/local-build.md
This PR addresses Issue #3486, focusing on improving accessibility for developers facing challenges with slow internet connections due to the large size of our repository. We're incorporating Blobless clones as a solution, which allows developers to significantly reduce the time and bandwidth required for cloning.
For more I attached Screenshots:
**- Cloning Results** 
**Local build  Resulst** 
- utilizing the --filter=blob:none option in the git clone command, 
- Details in Explanation
> Introducing Blobless Clones to Address Slow Internet Connections

- contributors.md
Adding Ceilidh Welsh, related to https://github.com/the-turing-way/the-turing-way/pull/3514
> Add Ceilidh Welsh to Turing Way contributors.md

- .github/workflows/crowdin-contributors.yml
- README.md
- book/website/afterword/contributors-record.md
Displays the Crowdin contributors table in the book, on the contributors record page, as well as in the README.md.
* Add Crowdin table tags to contributors record
* Update action to add table to README and contributors record
> Add Crowdin contributors table to afterword

- governance/community-calls/20240129-coworking.md
- governance/community-calls/20240205-coworking.md
- governance/community-calls/20240212-coworking.md
- governance/community-calls/20240219-coworking.md
- governance/community-calls/20240226-coworking.md
Adding notes from January 29, Feb 5, 12 & 19
> [Ready for Review] adding backlog of coworking call notes

- contributors.md
Updates my section in `contributors.md`.
> Update my bio

- book/website/community-handbook/communication-channels.md
Related to #3525 
* Expands the exiting communication chapter to add what was missing from our communication resources currently used
* Links mostly transferred from the start page
> Update communication-channels.md to add channel information

- contributors.md
Add Richard J. Acton to contributors.md
- Add Richard J. Acton to contributors.md
> Add Richard J. Acton to contributors.md

- README.md
Removes gitter link from our readme - addressing #3483 from @f-rower!
> Update README.md - remove gitter link

- book/website/community-handbook/accessibility/event-organising.md
Fixed header for events section of Accessibility section of Community Handbook
> Update event-organising.md - fixed header

- book/website/_toc.yml
- book/website/community-handbook/infrastructure/infrastructure-dns.md
Add a page explaining our DNS configuration.
* Brief introduction to DNS
* Explanation of DNS records
> Add sketch for DNS page

- contributors.md
Correcting formatting for Winny's bio.
> Update contributors.md to correct minor formatting

- governance/community-calls/20240304-coworking.md
- governance/community-calls/20240311-coworking.md
adds coworking notes from 4 march and 11 march 2024
> add coworking notes march 2024

- book/website/requirements.txt
Update to patched version of pillow. Closes #3601.
In _imagingcms.c in Pillow before 10.3.0, a buffer overflow exists because strcpy is used instead of strncpy. Update from 10.2.0 to 10.3.0.
> [Ready for review] Update to patched version of pillow. 

- project_management/quarterly_reports/2022-turing-tps-report.md
- Updating 2022 report
- Adding in Q1, Q2, Q3, Q4 reports
> Updating 2022 Annual Report Archive

- workshops/book-dash/meeting-notes/2023-09-05-WG.md
Part of addressing #3231 (does not fix obviously) 
* Adds notes from the meeting @EKaroune and @Arielle-Bennett had regarding Book Dash participation on 4 September
> Upload Book Dash WG meeting notes from September 2023 

- .zenodo.json
- CITATION.cff
* Setting to release the latest version of the book (see tag draft)
* Updated CITATION CFF, validated and update zenodo file
* Setting up a new release
> Citation cff updated and setting this PR for new version of the book

- governance/community-calls/20240408-coworking.md
- governance/community-calls/20240415-coworking.md
- governance/community-calls/20240422-coworking.md
- Added notes for 8 & 15 April to archive
- Added the new 'Apologies' section to the notes
> [Ready for Review] Added notes from april coworking calls - 8 and 15

- ways_of_working.md
Doing some slack gardening this week, finally updating this file: 
- @AlexandraAAJ - Not sure if the information that I've added for you is correct now (especially the percentage)
- @Arielle-Bennett - Updated your role to Programme Manager
- @eirini-zormpa - Added you to alumni! ❤️   
Is there anyone that should be added here, from TPS? We have quite a few new staff roles from TPS? (tagging you here @malvikasharan in case I'm missing anything or anyone!)
> Update ways_of_working.md document

- governance/community-calls/20240131-onboarding.md
- governance/community-calls/20240327-onboarding.md
- Added in these notes (removing answers to check-in questions!)
- Should we keep the debrief notes in the public archive?
- Thank you again @Susana465 and @da5nsy for cohosting! 🙏
> [Ready for review] Onboarding call notes

- workshops/github-workshop/2024-may-intro.md
> Update 2024-may-intro.md Add RichardJActon

- workshops/github-workshop/2024-may-intro.md
> Update 2024-may-intro.md with hui xin's details

- book/website/community-handbook/bookdash.md
Adding book-dash-collaboration image to book dash landing page
> Adding book-dash-collaboration image.md

- book/website/communication/open/education.md
A quick PR to add a resource to the Open Education overview
> Add a resource to Open Education

- book/website/collaboration/team-manual.md
A small addition of a resource, and moving a resource which got quite some critique due to the length to one of the other examples instead as prominent first example.
> Add a resource to team manuals (and move one)

- book/website/_toc.yml
- book/website/community-handbook/coworking/coworking-dropins.md
Fixes #3685 
* Add new chapter on Drop-in Sessions
* Add Scriberia image
> New Chapter in Community Handbook on Drop-in Sessions

- .github/workflows/validate_citation.yml
Add workflow to validate citation file when it has been modified
> Add workflow to validate citation file

- book/website/collaboration/academic-industry/academic-industry-establish.md
I think it was a small typo? "For Roche, the Data Study Group highlighted the research capabilities of the Turing Institute as well as importantly developing the initial relationship between Turing and Roche."
Fixes #<NUM>
> Tiny changes in academic-industry-establish.md

- book/website/_toc.yml
- book/website/collaboration/ambassador-schemes.md
- book/website/collaboration/ambassador-schemes/ambassador-schemes-establish.md
- book/website/collaboration/ambassador-schemes/ambassador-schemes-personal-story.md
Fixes #3636 
* I have written a new chapter on ambassador schemes. It consists of a landing page, a chapter on establishing and running a scheme and a case study on the Turing-Roche Community Scholar Scheme.
> Ambassador chapter [READY FOR REVIEW]

- book/website/collaboration/academic-industry/academic-industry-personal-story.md
- book/website/collaboration/ambassador-schemes.md
- book/website/collaboration/ambassador-schemes/ambassador-schemes-establish.md
- book/website/collaboration/ambassador-schemes/ambassador-schemes-personal-story.md
* Fixing some typos in ambassador chapter
* Adding in reference to ambassador scheme in Turing-Way academic-industry case study
> Ambassador chapter fixes

- book/website/foreword/background.md
- book/website/foreword/cite.md
- book/website/foreword/community.md
- book/website/foreword/embracing-digital-commons.md
- book/website/foreword/emergent-strategy.md
- book/website/foreword/faqs.md
- book/website/foreword/foreword.md
- book/website/foreword/governance.md
I just merged the Foreword section #2080  - but prematurely. I was doing all edits locally and I did not push the last set of changes suggested by Jessie.
This PR adds those changes.
> Adding proofrading comments on Foreword by Jessie

- governance/community-calls/20240103-collaboration-cafe.md
- governance/community-calls/20240117-collaboration-cafe.md
- governance/community-calls/20240207-collaboration-cafe.md
- governance/community-calls/20240221-collaboration-cafe.md
- governance/community-calls/20240306-collaboration-cafe.md
- governance/community-calls/20240320-collaboration-cafe.md
- governance/community-calls/20240403-collaboration-cafe.md
- governance/community-calls/20240417-collaboration-cafe.md
- governance/community-calls/20240501-collaboration-cafe.md
Redo of #3487 - adding collab cafe notes from january, february, march, april 2024
Importantly, I removed the 'check-in' question answers for folks, after speaking with our Data Protection Officer at the Turing!
> [Ready for Review] Collab cafe notes - Jan-Apr 2024

- book/website/collaboration/stakeholder-engagement.md
> Update stakeholder-engagement.md to fix RAM links

- governance/community-calls/20240515-collaboration-cafe.md
Add notes from collaboration cafe - may 15!
> [REVIEW FOR REVIEW] add collab cafe notes from 15 may

- book/website/reproducible-research/vcs.md
There's a missing `s` in this sentence
> Minor grammar fix to vcs.md

- book/website/communication/binder/zero-to-binder.md
This a simple typo that I noticed when reading the webpage. Would be nice to fix it quickly, especially since it's on the very first pages. Thank you!
> Update zero-to-binder.md - Fixing a typo

- book/website/_bibliography/references.bib
- book/website/collaboration/team-manual.md
adding another ten simple rules to improve research/lab culture to the end of the Team Manual section
> Update team-manual.md with a resource

- book/website/project-design/sdp.md
This fix is simply making text flow better.
> suggesting edit for better flow of text sdp.md

- .github/workflows/external_link_check.yml
> Fix external link check workflow

- book/website/communication/binder/zero-to-binder.md
Just a typo 
- [ x ] The following people should be added to the [table of contributors](https://github.com/the-turing-way/the-turing-way/blob/main/README.md#contributors) in the README file: myself (@ccoulombe)
> Fixed typo in zero-to-binder.md

- workshops/github-workshop/2024-nov.md
> Create Book Dash contributor list

- workshops/github-workshop/2024-nov.md
I've written my first md code
Fixes #<NUM>
> Update 2024-nov.md my name

- book/website/foreword/navigate.md
update alt text for navigating ttw image
Fixes #<NUM>
changed alt text
> Update navigate TTW image alt text.md

- book/website/reproducible-research/rdm/rdm-repository.md
Adding image with alt-text to data-repo image, together with minor fixes and removing a section without information
> Adding data-repo to rdm-repository.md

- book/website/community-handbook/translation/translation-workflow.md
Add more information about the new structure of the calls we have in the localisation team and decision making.
> Update ways of working in the localisation team

- book/website/communication/citable/citable-cff.md
Updated the figure caption to mention the source of the screen capture.
Fixed the missing link for Figure 98 in Software Citation with CITATION.ciff
> Update the description of Figure 98.md

- book/website/_bibliography/references.bib
- book/website/afterword/glossary.md
Indirectly addresses some of the discussion in https://github.com/the-turing-way/the-turing-way/pull/3705 about the definition of open source.
We didn't really come to a consensus in this previous discussion but I think these contributions may be clarifying to someone encountering these concepts and the related debates for the first time.
Here I've added some new definitions for terms that came up in the discussion about the definition of open source for related concepts and how they differ from one another.
I've attempted to adopt a descriptive approach to these definition giving an account of how they are generally used rather that attempting to prescribe any particular definition.
- Definitions added are in separate commits
- Some formatting fixes line newlines following the ends of …
> Glossary updates on Open Source and related concepts

- book/website/reproducible-research/vcs/vcs-workflow-branches.md
issue #3882 
update of figure captions and alt descriptions
> #3882 Update vcs-workflow-branches.md

- book/website/reproducible-research/vcs.md
issue #3882 
added image caption, updated alt text
> #3882 Update vcs.md

- book/website/collaboration/academic-industry/case-studies/practitioners-hub-case-study.md
Addresses @LelleDi's adventure in #3897
* Indent alt text
> Indent alt text for image description

- contributors.md
* Update contributors.md to add my details for contributions to Book Dash November 2024. This is associated with issue #3854 
* Add my Role
* Add my name
* Add GitHub ID
* Add ORCID ID
* Add Short Bio
* Add Personal Highlight
* Add Quotes
> add book dash contributor details

- book/website/afterword/collaborators.md
- contributors.md
Adding @Lextuga007 to Contributor Record and Collaborating Project
@lextuga007 - please feel free to edit this pull request to add your own testimony and any other information listed here!
> Adding Zoe and NHS-R project to collaborators

- contributors.md
* Update contributors.md to add my details for contributions to Book Dash November 2024. This is associated with issue #3854 
* Add my Role
* Add my name
* Add GitHub ID
* Add ORCID ID
* Add Short Bio
* Add Personal Highlight
* Add Quotes
> Update contributors.md with information of my Book Dash participation

- book/website/collaboration/academic-industry/intro-case-studies-and-best-practices-in-academic-industry-collaboration.md
> renamed title of industry-academia collab subchapter for easier navigation

- book/website/communication/citable/citable-linking.md
The link for 4 TU research data is updated in the Linking Research object chapter
Fixed the link for 4TU ResearchData
> Updated the link for 4TU ResearchData.md

- README.md
Found this needed change while updating the readme!
> Update README.md with Lelle's information

- contributors.md
Fixes #3655
Adds: @NoorhanAbbas, @chrisdburr, @mishkanemes, @lucyjstephenson, @giuliatomba, @amefonaffia, @aranas, @luisacutillo78
Updates: @EstherPlomp, @LizHareDogs, @sandygudie, @SaraVilla
> Updating Contributor record with June 2024 Book Dash contributors

- CONTRIBUTING.md
- contributors.md
Fixes #3854
Updates @LizHareDogs 
Adds @KatrionaGoldmann, @Preshh0, @seunolufemi123
> Updating Contributor record with November 2024 Book Dash contributors

- contributors.md
Updated bio and other information on contribution related to original PR #3951
* Corrections
* Added text related to my contributions to The Turing Way with and on behalf of the NHS-R Community
> Added more to Zoë Turner contribution text

- book/website/requirements.in
Addresses https://github.com/the-turing-way/the-turing-way/security/dependabot/15
> Update tornado version

- book/website/ethical-research/ethics-intro.md
Adding a small edit to the Guide for Ethics
> Update ethics-intro.md with colon

- README-translated/README-French.md
Fixes #3832 
- Fix broken links to all translated README.md
- Fix broken link to code of conduct
- Fix broken link to CONTRIBUTING.MD
> [Ready for review] Update README-French.md to fix broken links 

- book/website/reproducible-research/open/open-resources.md
Should address DOI links in: https://github.com/jupyter-book/mystmd/issues/1336
> Change doi.org base URL

- book/website/communication/research-objects.md
- book/website/community-handbook/coworking/coworking-dropins.md
- book/website/community-handbook/templates/template-bookdash-notes.md
- book/website/foreword/faqs.md
- book/website/project-design/data-governance/bigcode_casestudy.md
- book/website/project-design/sdpm.md
- book/website/reproducible-research/ci/ci-github-actions.md
- book/website/reproducible-research/code-documentation.md
- book/website/reproducible-research/code-documentation/code-documentation-project.md
- book/website/reproducible-research/code-reuse/code-reuse-packages.md
- book/website/reproducible-research/open/open-access.md
- book/website/reproducible-research/open/open-hardware.md
- book/website/reproducible-research/open/open-notebooks.md
- book/website/reproducible-research/rdm.md
- book/website/reproducible-research/rdm/rdm-elns.md
- book/website/reproducible-research/rdm/rdm-fair.md
- book/website/reproducible-research/rdm/rdm-visualisation.md
- book/website/reproducible-research/renv/renv-containers.md
- book/website/reproducible-research/vcs/vcs-git-in-research.md
- tests/lorem-ipsums.py
- tests/pull_files.py
> chore: fix more typos

- book/website/profiles.yml
Follow up to https://github.com/the-turing-way/the-turing-way/pull/4043 to help it pass CI.
> add .md to the end of the file references

- book/website/project-design/sdp/confidential.md
Fixing typo: project-design/sdp/confidential #4110
Fixes #<NUM>
*i fixed a typo error.*
* *i removed the word 'be' which was giving the sentence a gramatical error*
Avaga123
> Fixing typo: project-design/sdp/confidential #4110

- book/website/reproducible-research/rdm/rdm-data-curation.md
the file, with the heading “[Additional Resources on Data Curation](https://book.the-turing-way.org/reproducible-research/rdm/rdm-data-curation.html#additional-resources-on-data-curation)”, includes a link that doesn't work anymore. #4109 
Fixes #<NUM>4109
*.*
* *i replace broken link [Additional Resources on Data Curation](https://book.the-turing-way.org/reproducible-research/rdm/rdm-data-curation.html#additional-resources-on-data-curation) with a working one [10 Things for Curating Reproducible and FAIR Research](https://curating4reproducibility.org/10things/)..*
* * i also added reference ; Arguillas, F., Christian, T.-M., Gooch, M., Honeyman, T., Peer, L., & CURE-FAIR WG. (2022). 10 Things for Curating Reproducible and FAIR Research (1.1). Zenodo. https://doi.org/10.15497/RDA00074 …
> fixing broken link and adding referencing in Research Data Management/Data Curation notes

- .zenodo.json
- CITATION.cff
Zenodo has transferred ownership of the book's Zenodo record to theturingway@gmail.com.
I should be able to make a new release - testing if it's possible.
> Test new zenodo release

- book/website/ethical-research/ethics-open-source-governance.md
Adds some references to additional useful resources for thinking about this topic
* [Governing The Commons: The Evolution Of Institutions of Collective Action by Elinor Ostrom](https://archive.org/details/governingthecommons)
* [Elinor Ostrom's 8 Principles for Managing A Commmons](https://web.archive.org/web/20240411163813/https://onthecommons.org/magazine/elinor-ostroms-8-principles-managing-commmons/index.html)
* [Governable Spaces: Democratic Design for Online Life by Nathan Schneider](https://doi.org/10.1525/luminos.181)
* [The Tyranny of Structurelessness by Jo Freeman](https://web.archive.org/web/20240406094310/https://www.jofreeman.com/joreen/tyranny.htm)
> Add resources to the Ethics of open source governance chapter

- book/website/community-handbook/bookdash/bookdash-illustrator.md
Fixes #4106
*[TO EDIT]: Community Handbook/Working with an Illustrator*
* *Fixed typon in line 52.*
* *Update download count to 34,000 April 2025.*
> Typo and Download Count Update

- book/website/communication/citable/citable-orcid.md
- book/website/community-handbook/community-calls/community-calls-collabcafe.md
- book/website/community-handbook/style/consistency/consistency-formatting.md
- book/website/community-handbook/style/consistency/consistency-language.md
- book/website/community-handbook/style/consistency/consistency-structure.md
- book/website/community-handbook/style/style-videos.md
- book/website/ethical-research/data-hazards/dh-intro.md
- book/website/foreword/governance.md
- book/website/project-design/missing-data/missing-data-checklist-resources.md
- book/website/project-design/sdp/types.md
- book/website/reproducible-research/open/open-access.md
This pull request replaces HTML <iframe> embed codes with MyST Markdown {iframe} directives for consistency and easier management of embedded videos.
Fixes #4139
> Replaced iframe HTML tags with MyST iframe directive

- book/website/profiles.yml
Adding RCM pathway
Curating an RCM pathway
Fixes #<NUM>
add in all the file links and make file work!
> Updating profile file with RCM pathway

- book/website/profiles.yml
Adding new data stewards pathway
Curating chapters for data stewards.
Fixes #<NUM>
> New data stewards pathway

- book/website/community-handbook/local-build.md
- Fixes #4095
Updates local build instructions to reflect the current state of the local build
> Update local build instructions

- book/website/community-handbook/infrastructure/infrastructure-dns.md
- book/website/community-handbook/infrastructure/redirects.md
- netlify.toml
Updates DNS documentation and add redirect documentation to reflect changes in #4045
- Add page describing redirects
- Update DNS page to refer to redirects
- Update redirects
- Remove unnecessary http->https
- Add missing www.the-turing-way.org -> start page
> Update DNS and redirect documentation

- book/website/reproducible-research/open/open-scholarship.md
Associated with #4209 
* Sample change to citizen science page
> Demo update open-scholarship.md to remove dead link

- README.md
The promotion pack link was updated from https://github.com/the-turing-way/the-turing-way/tree/main/communications/promotion-pack to  https://github.com/the-turing-way/communications/tree/main/promotion-pack. 
* Update promotion pack link.
> Update README.md to include the updated promotion pack link.

- book/website/myst.yml
> Fix TOC: typo in filename

- .github/ISSUE_TEMPLATE/config.yml
Resolves https://github.com/the-turing-way/the-turing-way/issues/4025
> Add `https://` to link

- book/website/community-handbook/infrastructure/infrastructure-dns.md
- book/website/community-handbook/infrastructure/infrastructure-redirects.md
- netlify.toml
Closes #4243 
Adds helper redirects to `netlify.toml` and document the DNS and redirect configuration.
> Move DNS-implemented redirects to webserver

- book/website/reproducible-research/vcs.md
Fix typos. Add a space between “tools” and “in”. Also removed a double space after "introduce".
Pinging @KirstieJane for review.
I found a few typos on the [vcs page](https://book.the-turing-way.org/reproducible-research/vcs) of the book! I made a fork of the book, edited it, and am now opening a pull request to review my changes.
* *Fix a typo by adding a space between the words “tools” and “in”.*
* *Fix double space after "introduce" by removing one of the spaces*
> [Fix Typo]: Fix typos in vcs page

- book/README.md
> Update Netlify docs to remove pathways reference

- book/README.md
> Update book directory README

- README.md
@stefanv found a figure that was missed in #4274 😄 
* update path to logo in README file
* update link as welcome page doesn't exist any more
> Fix logo not showing in README

- book/website/myst.yml
- book/website/references.bib
- book/website/reproducible-research/rdm/rdm-smp.md
We started the discussion about having a Section on Software Management Plans in #2419. After some discussion, we created a first draft with input from those involved in the issue. After a bit of editing and proof reading, I think it is ready to be published (and we can improve it in the future).
Fixes #2419
* A new section on Software Management Plans :-)
@RichardJActon, @EstherPlomp, @JaroCamphuijsen, and @bakhshir contributed to the creation of this chapter.
> Smp chapter

- book/website/reproducible-research/testing/testing-overview.md
Fixes #4092
Fixes several broken links on the testing overview page.
* Updates links to valid MyST syntax.
> Fix links in testing overview

- README-translated/README-German.md
The German README had some issues which are fixed by this pull request.
> Fix German README

- book/Makefile
- book/website/myst.yml
Resolves #4346 
Not sure how/if possible to not even generate the thebe files, that's an upstream issue and we have that cleanup hack in other repos, too.
> MAINT: remove the launch button
