the-turing-way/the-turing-way

- chapters/version_control.md
Pull request my fork's version control branch -> alan turing's version control branch. If merged I'll then merge it into turing master after checking it still displays right on the version control branch.
Previously the version control chapter was in the root directory, but it has been moved to the chapter's directory. As a result the links to the figures the chapter contains were broken. This request corrects them.
> Fix broken figure links

- project_management/turing-webpage.md
A couple of additions to the proposed website content. Contributes to #41.
* Add workshop titles and sign-up links. ~~At this point, I haven't included a blurb but can add/borrow one from the promotional emails later.~~ Edit: Workshop descriptions added after feedback from @sgibson91 and @r-j-arnold.
* Add link to newsletter sign-up.
* Add content for a widget describing the contrinutions of the Research Engineering Group. This will show up as a small extra section at the bottom of the page (see examples [here](https://www.turing.ac.uk/research/research-projects/evaluating-homomorphic-encryption) and [here](https://www.turing.ac.uk/research/research-projects/security-cloud)).
* @sgibson91, could you read over the REG widget section as I've written a sentence about your work on the …
> [quick-fix] Website update

- CONTRIBUTING.md
The link was giving a 404 error as it was directing to an old address I guess. I replaced it with the functioning link of the gitter badge on README
> fix broken gitter link

- chapters/reproducibility.md
- chapters/version_control.md
- templates/CHAPTER_TEMPLATE.md
In the chapter template and in both chapters already in master move the chapter prerequisites to the start of the chapter. Previously they came after the summary and why the chapter was useful which can be a lot of text. There's no point wasting a reader's time introducing them to a topic they do not yet have the foundations to grasp.
- Whether they think this is a good idea
> Move prerequisites to start of chapter

- CONTRIBUTING.md
- chapters/open_research.md
- figures/figure_list.md
As discussed with @pherterich in #175 it's just as important for disciplines outside of science to work openly and reproducibly, and the vast majority of the principles for doing so are the same (e.g. keep your data open, share any analysis code etc). 
As such change the open science chapter from being about open *science* to being about open *research*.
This change has been made on a new branch called open_research, which is up to date with both master and the open_science branch. If/when this pull request is accepted the open_science branch should be deleted to prevent further development on it. Future development of this chapter should take place on the open_research branch.
Rename the open science chapter to open research.
Change references to "open science" within the chapter to …
> Change "Open science" chapter to "Open research" chapter.

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Doesn't close any open issues
I find the white lines in the PR and issues templates really off putting - I don't think its clear where the html comment ends and the open text begins.
This PR removes all whitespace from inside of the html comments. The goal is to make it easier to quickly skim over the comment while still providing the information needed for new folks!
* Remove whitespace in issue and PR templates
> Remove white lines from issue and PR templates

- humans.md
Addition of a contributor. Doesn't close any open issues.
* Add Oliver Strickson (@ots22) to `humans.md` to acknowledge his contribution of notes around containers.
> Add Oliver Strickson to humans.md for Container notes contribution

- .github/PULL_REQUEST_TEMPLATE.md
Humans.md has been renamed to contributors.md. Reflect this in the pull request template.
Have I missed any other links to humans.md that need fixing? I think I've checked all the files, but if you remember humans.md being referenced anywhere else please correct me.
> [Quick fix] Change humans.md link to contributors.md link

- chapters/open_research.md
In the first paragraph of the **Open Research** chapter, there is a link to a paper defining the term *open research*.  The link text in the sentence is the single word *is*.  This is bad practice because it gives the reader little indication as to where the linking is pointing.  Instead the link text should give some indication of what material is being linked, which is what this PR proposes.
*  Make the link text the handful of words earlier in the sentence.
*  Spell out what OECD stands for in case readers don't know.
*  Include additional information (in this case the name of the paper and its source) in the link mouseover text.
Nope, but I am listed as a contributor on the `README.md`.
> Make Link Destination Apparent

- .github/ISSUE_TEMPLATE/CHAPTER_ISSUE_TEMPLATE.md
A value is required for the 'about' key in the yaml heading of the issue
template for Github
This PR is a hotfix to a merged PR #488 and which is linked to issue #476 
Fixes #476 
This PR fixes this error that is generated by Github:
> [HOTFIX] Updating 'about' key as this required by Github

- .github/PULL_REQUEST_TEMPLATE.md
* Adjust acknowledging contributors section to point to table of contributors instead of contributors.md file.
* Put html comments all on the same line. GitHub will wrap them nicely 😄
Doesn't close an open issue.
Our PR template doesn't make sense now that we use the all contributors bot rather than asking people to manually add themselves to the contributors.md file. Hopefully this fixes it!
* Adjust acknowledging contributors section to point to table of contributors instead of contributors.md file.
* Put html comments all on the same line. GitHub will wrap them nicely 😄
> [Ready for review] Change contributors acknowledgment in PR template

- workshops/build-a-binderhub/binderhub_resources/setup.sh
- workshops/build-a-binderhub/workshop-presentations/zero-to-binderhub.md
This PR addresses the issues raised at the Reactor Sprint around the clarity of the Zero-to-BinderHub workshop.
Fixes #529 
* Add alternative login command
* (Try to) Explain where extra resource groups come from when deploying the Kubernetes cluster
* Remind users to delete extraneous resource groups when tearing down the deployment
* Edit `config-template.yaml` to prevent `setup.sh` from hanging during execution due to a misplaced comment
* Add clearer steps for editing `setup.sh` and `config-template.yaml` when parsing the JupyterHub IP
> [Ready for Review] Update the BinderHub Workshop document

- book/content/reviewing/reviewing.md
Added additional content in order to point out some more tips on how to make code reviews even more friendly, efficient as well as how to avoid subjective disagreements. 
Just check if the new text fits with the old one. I checked for repeated content but another eye to ensure nothing is repeated may be useful.
- [ x] all contributors to this pull request who wish to be included are named in [contributors.md](https://github.com/alan-turing-institute/the-turing-way/blob/master/contributors.md).
> [Ready for review] Updates to A Reviewing section

- CONTRIBUTING.md
- book/website/docker-compose.yml
Fixes #590 
* Adds a `docker-compose.yml` file based loosely on https://jupyter.org/jupyter-book/guide/03_build.html
Local development can be achieved using:
```
cd website
docker-compose up
```
This will:
1. Install all custom ruby gem requirements
2. Serve the book site on `http://0.0.0.0:4000/`
> [WIP] feat: Add docker-compose file

- book/content/glossary/glossary.md
- book/website/_data/toc.yml
Addresses (but does not close): #598, #616
Add a centralised glossary.
* Adds a centralised glossary.
* Adds a proof-of-concept script for checking links to glossary items:
1. We want to be able to link from the main text to glossary items.
2. We want to know when we've used a term in the text but have forgotten to link to the glossary.
> feat: Add basic glossary placeholder

- .pre-commit-config.yaml
- .prettierignore
- .travis.yml
- CONTRIBUTING.md
Addresses (but does not close) #630
> [Ready for review] Add auto formatting via prettier

- book/website/requirements.txt
Doesn't fix an open issue 😭 (although I've now made #692 to implement a better fix)
Jupyterbook has updated and its ended up breaking our CI a bit. So this hot fix sets jupyter book's version to a specific release (0.5.2)
* @alexmorley's update to `requirements.txt` that I've cherry picked from #687
> [Quick Fix] Update requirements.txt to pin Jupyter Book to v 0.5.2

- book/content/credit/credit.md
Quick fix to remove the remaining template boilerplate from the chapter on Credit for Reproducible Research.
> Remove template text from the chapter on credit

- CODE_OF_CONDUCT.md
This fixes a word in the COC, I think from an earlier version that referred to a single person instead of a group
> COC: her -> their

- book/content/testing/testing.md
Update R testing frameworks. `testthat` is the most used framework and its development is active, `tinytest` is also active, but `Runit`'s last release is more than a year old (some packages like RcppArmadillo have rewritten their tests recently to stop using Runit).
* Remove `Runit` from the R testing frameworks list
* Add `testthat` and `tinytest` to the R testing frameworks list
> Update R testing frameworks

- .all-contributorsrc
- README.md
Will fix #892.
- Move tags that mark the area of the README that the all-contributors bot can change.
- Remove flat, square styling from the badge template (as is the current default).
> Fix all-contributors config

- README.md
Another follow-on from #893 - this PR moves the all-contributors badge to the end of the row so that the marker for the end of the badge doesn't cause a line break between other badges.
> Move all-contributors badge to end

- book/content/make/make.md
At the moment, the chapter on Make  does not demonstrate how to actually include tables into a manuscript, and the way it is done in the linked GitHub repo can be hard to understand.
In this PR, I try to demonstrate how the example paper does it, and also include an alternative way of doing it with LaTeX variables. For both approaches, I have included simplified demonstrations.
Fixes #854 
* Add another reason for using Make (flexibility)
* Add section "Including numerical results and tables"  just before the Further Reading of the chapter.
> Add demonstrations of including tables into Make chapter

- book/website/_config.yml
This PR updates the page footers of the book to link to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) of The Turing Way.
Fixes #929 
* Instead of ponting to the jupyter-book contributors, the footer of the book's pages now points to the Turing Way contributors
> Change pages footer to link to Turing Way contributors

- tests/no-bad-latin.py
* Add "et cetera" to the list of bad Latin phrases checked for on CI
> Add "et cetera" as a deprecated Latinism

- .all-contributorsrc
This PR adds Bouwe Andela as a contributor.
@bouweandela - I'm so sorry for all the notifications 😩 
The PR also sorts the table alphabetically. MASSIVE thanks to @alexwlchan for that contributions to All Contributors! https://github.com/all-contributors/all-contributors-cli/pull/249
> (Finally) Add bouweandela & sort alphabetically

- book/content/po/toc.yml
- book/website/scripts/multilingual_make.sh
`multilingual_make.sh` uses cached table of contents instead. This is to decoupled already generated po files from updates of the source table of contents.
Modify source location of toc.yml in the multilingual_make script.
> multilingual make uses cached table of contents instead

- .github/ISSUE_TEMPLATE/CHAPTER_ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
This PR is updating the issue templates for the repository.
* Added a config.yml file which will include links to the collaboration cafe documentation and gitter chat, alongside the new chapter and general issue templates
* Added a bug report template so it's clearer how people should report unexpected behaviour
* Updated (emojified) the general and new chapter templates
> [Ready for Review] Updating Issue Templates

- book/content/version_control/version_control.md
Link for doing pull request via terminal was https://git-scm.com/docs/Git-request-pull which gave 404 and then redirected to general docs page. Changing the link to https://git-scm.com/docs/git-request-pull fixed it (small case *g*)
Fixes #<NUM>
*Fixing broken link to https://git-scm.com/docs/git-request-pull*
* https://git-scm.com/docs/Git-request-pull changed to https://git-scm.com/docs/git-request-pull
> Fixing broken link https://git-scm.com/docs/git-request-pull

- CONTRIBUTING.md
Fixes #1016 by removing dangling reference to `docker-compose.yml` in `CONTRIBUTING.md`.
Just one very simple change: removes reference to `docker-compose.yml` that was removed a while ago.
I think the idea of running locally is very valuable. Furthermore, I am currently unable to run the book locally on my Fedora 31 machine without `Docker` or `podman`. I would be interested in proposing an alternative Docker configuration, especially since this book advocates for using containers. I am very interested in discussing other possible solutions!
> Fixes #1016 - remove referece to non-existent file from CONTRIBUTING.

- CONTRIBUTING.md
- book/README.md
> Added jupyter book links and corrected path for figures

- book/content/research_compendia/research_compendia.md
**Fixed the link error of ```Reproducible Environments```, ```Binder Hub```, ```Reproducibility with Make``` in the [Prerequisites / Recommended skill level](https://the-turing-way.netlify.app/research_compendia/research_compendia.html#Prerequisites-/-recommended-skill-level) of Research Compendia.**
> Link for subsections does not work as I expected. See screenshot from https://the-turing-way.netlify.com/research_compendia/research_compendia.html 
Fixes **#1003** & **#1004**
> Improve research compendia Chapter : Fixed Broken Links

- CODE_OF_CONDUCT.md
*Minor corrections which fix some links*
Fixes the following links in the [Code of Conduct](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md) file :
* [2.1 Expected Behaviors](https://github.com/srishti-nema/the-turing-way/blob/master/21-expected-behaviours)
* [4 Enforcement Manual](https://github.com/alan-turing-institute/the-turing-way/blob/master/CODE_OF_CONDUCT.md#enforcement-manual) at the end of Section 2.3
* [xvzf Code of Conduct](http://xvzf.io/) given in Section 5
> fix broken links in CODE_OF_CONDUCT.md

- .github/workflows/ci.yml
- book/README.md
This disables the HTML proofer from the CI introduced in #1073. 
The proofer should be brought back once the broken links are fixed.
- [X ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
> Comment out the html proofer

- README.md
Due to the book reformat, our team photo was no longer rendering in the readme. This PR fixes that :smile:
* Update team photo reference in readme
> Bugfix: Fix team photo in readme

- book/website/_toc.yml
- book/website/reproducible-research/ci/ci-options.md
- book/website/reproducible-research/ci/ci-travis.md
Fixes #927
This is a new version of PR #1070, based on most recent master.
The CI chapter currently focuses (mostly) on Travis, while other services (CircleCI, Github Action) are becoming very good alternatives. This PR adds more alternatives and links to examples on how to use them
Alternatives to be considered:
> Changes from List of continuous integration services #1070

- book/website/reproducible-research/code-quality.md
`lintr` is an R package and `prospector` is a python package.  They were reversed.
> Minor mistake in code-quality.md

- book/website/reproducible-research/rdm/rdm-spreadsheets.md
Whilst reading this chapter online, I noticed the list of ways to make a dataset look tidy appeared formatted strangely, and figured it had to do with the | symbol. I have also removed the "3." from the only title that seems to be numbered.
* Remove "|" from numbered list
* Remove "3." from one of the titles
> Minor update for rdm-spreadsheets.md

- book/website/reproducible-research/rdm/rdm-metadata.md
This would enable relative linking with the new data management plan section
Fixes #1043
* add a relative link for the metadata and documentation section
> update relative link for rdm-metadata.md

- tests/lorem-ipsums.py
- tests/no-bad-latin.py
When running CI in PRs, CI will fail with a `FileNotFoundError` if the PR deletes a file. This PR adds a `try/except` block to try to circumvent this. It could probably be handled more elegantly with something in the JSON packet from `pull_files.py`, but this should work for now.
* `try/except` blocks added to `lorem-ipsums.py` and `no-bad-latin.py`
> Fix PR-based CI to account for files that have been deleted

- book/website/community-handbook/style.md
- book/website/community-handbook/style/style-figures.md
This PR removes the auto-formatting section of the [style guide](https://the-turing-way.netlify.app/community-handbook/style.html). This section describes using a pre-commit hook and prettier.io, which were formerly part of the project but later removed in #908.
Fixes #1390 
* Remove auto-formatting section
> Remove auto-formatting section and outdated image referencing in the style guide

- book/website/reproducible-research/ci/ci-options.md
- book/website/reproducible-research/overview/overview-resources.md
Fix non-consecutive headers
Fixes #1421 
* reproducible-research/ci/ci-options.md
* reproducible-research/ci/ci-options.md
> Fix non-consecutive headers: CI subchapters

- book/website/_config.yml
- book/website/_static/myfile.css
- book/website/requirements.txt
After a discussion in slack regarding the book-layout, @lauracion and @SamGuay suggested implementing [hypothes.is](https://web.hypothes.is/). I gave it a try and made changes in `_config.yml`. After that, I tried to build up the Jupyter book locally and it worked. It became easy to highlight any text and to add any notes in the book.
* *Implementing [hypothes.is](https://web.hypothes.is/) in the TW book .*
> Upgrade Jupyter Book / Enable collaborative annotation in the book

- book/templates/case-study-template/case-study-template.md
- book/templates/chapter-template/README.md
Fixes #<NUM>
Github does not recognise the way I implemented relative links in the chapter and case study templates. I have updated the links accordingly and they work now. I also caught a piece of repeated text in the chapter template, which I have removed.
- Correct broken relative links
- Remove repeated text
> Fix broken Relative Links in Chapter and Case Study templates

- .github/workflows/ci.yml
Fixes #1594 
This PR is adding a matrix strategy to our Jupyter Book CI workflow so that the build is tested on different OSs (ubuntu, windows and mac os) and versions of python (3.7 and 3.8).
Container-based actions are not supported on Mac and Windows (I can't find a good reference for this from GitHub), so HTML proofer won't run on those OSs in the matrix. This may influence our decisions in the next section.
🚨 These will need to be done before merging 🚨 
- The `ci.yml` GitHub Actions file has been updated to include matrix strategies for OS and Python version
- The fail-fast strategy has been set to false so one failed job doesn't halt all jobs
- The default shell for all jobs has been set to bash (this is particularly important when building on windows)
> Update CI to check multiple OSs and Python versions

- book/website/_toc.yml
- book/website/community-handbook/style/style-custom-styling.md
Fixes #1657 
* In a merge conflict, this file was lost which I may have overlooked, restoring it in this PR
* Restoring the subchapter on custom styling by @paulowoicho
> restore custom styling chapter under style guide

- book/website/reproducible-research/renv/renv-binder.md
Remove duplication of the list under subheading "Disambiguation".
On lines 83-86 there is a duplicate version of the list under the Disambiguation subheading. There is a version where points are bold, and one where they are not. 
* Remove the unbolded version of the list.
> Remove duplication of "Disambiguation" list

- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-julia.md
- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-python.md
- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-r.md
- workshops/boost-research-reproducibility-binder/workshop-presentations/zero-to-binder-solo.md
This PR changes `master` branch references in the Zero to Binder tutorials to `main` or `HEAD`.
* The Zero to Binder tutorial files (in all language flavours)
> Change master branch references to main or HEAD

- book/website/figures/_figure-list.md
Updating to add the scientific union badge image to the list
Hopefully this fixes the error with images in the Activism chapter! 
add scientific union badge to the list of figures
- [X ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
> Update _figure-list.md - add scientific union badge to the list 

- CODE_OF_CONDUCT.md
This PR fixes a broken link in the code of conduct's table of contents.
I have also checked that all other links in the code of conduct work.
PS I didn't open an issue because I felt the change was so small it didn't merit one. I couldn't see and existing issue or PR for this problem. Do say if that causes problems for you.
-  Fix broken link to expected behaviours section in the code of conduct's table of contents
> Fix link in table of contents

- book/website/community-handbook/style/style-crossref.md
The example label directive on line 58, "(rr-overview=)" should have the equals sign on the outside of the parentheses.
* Update label directive
> Fix example label directive to have ")=" at the end

- book/website/reproducible-research/renv/renv-containers.md
* On lines 412 and 413, we have two separate blockquotes for the Singularity prerequisites note. I think this would look better compressed into one blockquote. Also, Singularity Desktop for macOS is now in Beta stage, I think that could also be changed.
* Compress two blockquotes into one
* Update "alpha preview" to "beta" for the Singularity macOS Desktop app.
> Compress two blockquotes into one

- workshops/boost-research-reproducibility-binder/paired_examples.md
The paired example for the (Boost your research reproducibility
workshop) that uses R no longer works/builds on mybinder.org due to
upgrades to repo2docker. We note this in the markdown file listing the
paired examples.
* `workshops/boost-research-reproducibility-binder/paired_examples.md` edited
> Remove R example from paired examples for workshop

- book/website/collaboration/new-community/new-community-guide.md
The reference Matrix client Riot was renamed recently to Element, and the website address changed too. This minor tweak updates the new community guide to reflect that.
> Update link to reflect renaming of Riot to Element

- book/website/reproducible-research/vcs/vcs-github.md
Fixes small grammatical error regarding noun determiner.
* On the Netlify-hosted _Turing Way_, the numbered list indices are reset because of the code blocks at each point. This means the list looks as below, with 1. as the index for all points. To fix this, indent the code blocks with 4 spaces.
> Indent numbered list blocks to avoid number reset

- project_management/turing_mybinder_role.md
This PR adds a document that describes the minimal responsibilities required of the Turing mybinder Federation cluster administrator, a role that has so far been filled by @sgibson91.
* Add `project_management/turing_mybinder_role.md`
> Describe minimal responsibilities of Turing mybinder Federation administrator

- book/website/welcome.md
I have worked on issue #1877 to add the chapters image to the welcome page. 
- Adding TheTuringWayChapters.jpg image to the welcome page
- Is this the correct place to put it? 
[ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file.
[-] The following people should be added to the [table of contributors](https://github.com/alan-turing-institute/the-turing-way/blob/master/README.md#contributors) in the README file: <lottycoupat>
> Adding Turing Way chapters image.md

- book/website/reproducible-research/open.md
Adding open research image
Fixes #<NUM>
Adding open research image
adding link to image in md file
adding alt text
> Adding link to open research image

- CONTRIBUTING.md
Fixes #1865
*Replaces broken link to Leicester Study Skills PDF.*
* *Fixed link.*
* *Add alternate link for zipped html option.*
* *Slightly rephrased copy to cover both options.*
> Fix link to University of Leicester Study Skills

- book/website/_toc.yml
- book/website/reproducible-research/open/open-data.md
Adding data-privacy image in the Open Data page.
Fixes #1881
* Adding an image.
> Adding an image in the Open Data page

- tests/no-bad-latin.py
- tests/pull_files.py
We see a latin check failure with a matching pattern in one of the new images added in #1588 
This PR fixes the CI scripts to ignore those files. Locally however I could not reproduce the match with that image file (I assume the encoding might work differently than in the VM), so first I pull the whole pull request. If CI is all green I'll remove all unrelated commits to keep the infrastructure changes only.
> Fix: CI latin check should ignore binary images

- book/website/welcome.md
as per #1955, to make it less intimidating (#1851, #1919, probably others) and to direct readers to the recommended ways of interacting with the guide (browse or keyword search).
- I've tried to cut down the initial message to the bare minimum
- I've moved out some of the text into a new 'history' section. **This would need expanding or removing before a merge** - it is currently a [stub](https://en.wikipedia.org/wiki/Wikipedia:Stub#Basic_information). I imagine this could be a good place for origin stories, key people, funding thanks etc. This interacts with #1731 - probably makes sense to include a link to a fuller history rather than have a duplicate 'history' on the landing page, unless the plan was for it to be there anyhow.
- I've cut words where I could.
- I've tried to keep the …
> Updating the landing page

- book/website/reproducible-research/vcs/vcs-github.md
This just provides a minor cleanup to be self-consistent with naming and protocol to be used (https vs ssh), and removes links put under `here` words, which is widely considered avoidable. 
I avoided making contextual changes as it should be preceded by a discussion in #1489 and #1490 
* use ssh, and consistent repo and user naming in git examples
* refactor links to not to be for "here"
> Minor cleanup for the github workflow page

- book/website/_toc.yml
- book/website/requirements.txt
~~Seeing if updating the jupyter book version fixes https://github.com/executablebooks/jupyter-book/issues/1392 / https://github.com/alan-turing-institute/the-turing-way/issues/2034#issuecomment-885987020~~ **Update: it doesn't.**
~~I don't actually know if just changing this line will update the version of jupyter books used (early stage of learning), but I thought I'd try it out on a branch and have a look at the netlify preview to see.~~ **Update: it does.**
I have updated the jupyter book version to the latest version and fixed the obvious breaks it caused.
The main thing was that it [required an update to the fields in the toc](https://executablebooks.org/en/latest/updates/2021-06-18-update-toc.html).
I have checked:
- Others involved in previous jupyter book upgrades …
> Update jupyter book version to 0.11.2

- book/website/reproducible-research/testing/testing-guidance.md
Despite many people thinking that C++ is compatible with C, this is not true in the modern language as C99 diverged, introducing features that were not available in C++ and vice versa. This has continued, with C11 introducing further incompatabilities. This means that you can only universally use a C++ testing framework if you restrict yourself to the C89 standardwhich is obviously now 32 years old!
Because of that, using a C++ testing framework for a C project can run into issues. This is not obvious at first glance, but consider the following which my be present in a header file which would need to be included in a translation unit for a C++ testing framework to make use of a C library:
```
// 'restrict' is not a keyword in C++ so this generates a compiler error:
void myfunction(double* …
```
> Remove advice to use C++ testing frameworks for C

- book/website/project-design/project-repo.md
Fixing links at the start of the 'Creating repositories' chapter
- Changed names for links to subchapters
> Correcting names for links to subchapters

- book/website/reproducible-research/make/make-examples.md
The example makefile was filtering out all input csv files which results in an empty `DATA` variable.
Instead I think the intent is to keep only input csv files (though it is a bit redundant, since one could just use `INPUT_CSV` directly, but I assume this is for educational purposes)
Also fixes pattern substitutions, since these where generating `figure_input_file_{N}` instead of `figure_{N}`.
Would be good to actually run the files as tests in CI
> fix makefile

- README.md
Hi Turing Way! This is a little PR updating some info on the README about citing the illustrations - I see there are some open issues about the README so no worries if you're not looking to update it at this time :)
Noticed the info in the README about how to use the illustrations is a little out of date, and links to one of the older zenodo repos. 
This PR updates the links and info in the Citing the Illustrations section: 
* Adds the dates of the two latest online book dashes. 
* Changes the link to the illustrations from a specific version to the DOI so that the link always resolves to the latest repository of images. 
* Updates the example citation with the latest version information.
> Update README info for citing illustrations

- book/website/reproducible-research/open/open-data.md
Addressing this issue (https://github.com/alan-turing-institute/the-turing-way/issues/2085)
This should fix issue [#2085](https://github.com/alan-turing-institute/the-turing-way/issues/2085). I believe this extra space between the cite brackets and citation name is causing the issue on the Open Data page.
Fixes #2085
- Remove Space
- I am unable to run this on my local machine atm to confirm the fix, but wanted to suggest this chance asap to address the issue
> fix EU2016protection link

- .zenodo.json
To comply with their controlled vocabulary, I am changing Book to Publication: https://developers.zenodo.org/#representation (No other option seem to work)
> Update .zenodo.json - upload type "Book" -> "Publication"

- book/website/_toc.yml
Fixes a typo I noticed in the spelling of "acknowledgements" in the TOC for Community Handbook > CoC  > Acknowledgements 
* replaces "acnowledgements" with "acknowledgements"
> Fix typo on CoC acknowledgements title

- .github/workflows/release-drafter.yml
- .github/workflows/release-workflow.yml
- tests/release_workflow.py
- tests/requirements.txt
CITATION.cff is a valid YAML file, so we use the ruamel YAML parser to
read/edit/write the file instead of manipulating individual lines.
Additionally added the workflow_dispatch trigger to the release-drafter.yml workflow file for testing
> Refactor release_workflow.py to use a YAML parser

- CITATION.cff
Having this field in the file causes weird changes when we run `cffconvert` to generate a `.zenodo.json` file. See: https://github.com/alan-turing-institute/the-turing-way/pull/2411#discussion_r882534240 The citation file is still valid according to `cffconvert --validate`
> Remove given-names field in CITATION.cff file

- README.md
Just a tiny mini typo that bothered me.
> Fix tiny mini typo in main README.md

- book/website/reproducible-research/rdm/rdm-fair.md
Under the heading 'Theory' and the word 'Findable', changed the reference to data from being plural to singular ("them" --> "it" and "are" --> "is"
Fixes #2486
In the paragraph: 
The first step in (re)using data is to find them! Descriptive metadata (information about the data such as keywords) are essential.
Change:
*  "them" to "it"
*  "are" to "is"
> Style/grammar correction in rdm-fair.md

- .github/in-solidarity.yml
Tweaking the 'in solidarity' settings to create a special case that allows the word "master" to be used, only in the situation whereby it is immediately preceded by a "/", as seen in https://github.com/alan-turing-institute/the-turing-way/pull/2339 and described in #2343.
Currently seeking two specific types of input:
- Is this a good idea?
- How do we test that this works? (I can't see how to test this without approving it and then purposefully doing other PRs which should pass/fail and seeing whether it works as intended, but I'd prefer to test it without having to approve this PR)
> [WIP] update in solidarity to allow for hyperlinks to repos that use "/master"

- .github/workflows/close-talk-issues.yml
- Finds all issues with 'talks-and-workshops' labels
- Closes any of these issues whose talk date is in the past
- Either, creates a new issue to promote the closed talk issues in the
newsletter and assigns the community manager to it,  or...
- Adds a comment to an existing newsletter issue with newly closed talk issues
The idea behind creating a new issue that lists closed talk issues is to reduce the number of pings the Community Manager receives. Similarly motivated is commenting on an already existing issue, rather than opening a new one.
* close-talk-issues.yml
> Automate closing talk issues in a workflow

- .github/ISSUE_TEMPLATE/give_a_talk.yml
- added link to TTW slack in the issue template for 'give ttw talk'
> added link to slack to 'ttw slack' issue template

- .github/workflows/ci.yml
3.7 is no longer supported by newer versions of numpy.
https://github.com/alan-turing-institute/the-turing-way/pull/2592#issuecomment-1229036518
> Bumping the version of python used in CI to 3.10

- book/website/_bibliography/references.bib
Part of #2611 
```
←[91mC:\Users\cege-user\Documents\the-turing-way\book\website\afterword\bibliography.md:6: WARNING: missing journal in kairouzAdvancesOpenProblems2019←[39;49;00m
```
> add `journal` field to supress jupyter-book warning

- book/website/project-design/sdpw/pd-sdp-private-learning.md
```
the-turing-way\book\website\project-design\sdpw\pd-sdp-private-learning.md:32: ERROR: Unknown interpreted text role "ref:ps"
```
Part of #2611 (same issue as #2620)
> Fix referencing syntax

- book/website/reproducible-research/open/open-access.md
Formatting fix as part of #2611.
Was meaning that an image didn't display.
```
←[31mC:\Users\cege-user\Documents\the-turing-way\book\website\reproducible-research\open\open-access.md:106: ERROR: Directive 'figure': Invalid options YAML: while scanning a simple key
in "<unicode string>", line 4, column 1:
The **gold and diamond** routes  ...
^
could not find expected ':'
in "<unicode string>", line 5, column 1:
^
---
height: 500px
name: routes-to-OA
alt: An image of a train showing the routes to open access publishing. The green route is signalled as free and shows a preprint server at the start of the journey and self archive at the end.
The **gold and diamond** routes are signalled as author pay and funder or institution pay and show the publish in an open access journal part of the …
```
> fix broken alt text formatting (must be on one line)

- workshops/README.md
This Pull Request fixes #2697 by adding in a description about the contents of the folder so that it reflects that the folder also has content about github workshops. 
* Made edit to description
> Added GitHub workshops to README

- .all-contributorsrc
In order to better facilitate adding lots of new contributors during Hacktober, and more generally, I propose turning off CI for allcontrib PRs. This shouldn't open us to any risk (they still need to be reviewed), but it means that they can be quickly reviewed, and so it's less likely to get backed up.
This undoes #1021, which shouldn't be an issue anymore since we no longer use Travis.
> Set skipCI to true

- book/website/community-handbook/contributing.md
Contributes to #2674
Contributes to #2611 
Restore the "Contributing and Developing Chapters - Templates and Workflow" top level page, fixing toctree warnings.
This page was removed in 0af3a92a. I think this may have been a mistake as the other pages in the chapter, and the figure, remained in the repository.
* Restore the chapter's introductory page
> Restore contributing chapter

- book/website/reproducible-research/rdm/rdm-spreadsheets.md
This tip was formatted as code, which seems to be a typo:
This commit adds the `{tip}` admonition tag.
> fix formatting of tip block

- book/website/_bibliography/references.bib
- book/website/community-handbook/presenting.md
On build we get these two warnings:
- `WARNING: missing journal in Horbach2022openreview`
- `WARNING: missing journal in Tsai2016qualdata`
Working towards #2611.
This is blocking #2838.
I added journal fields to these two references.
_Minor vent: the whole idea of something having to be in a journal to be considered an "article" is so last century..._
> Add journal fields to 2 references

- book/website/community-handbook/presenting.md
During book build we receive the error:
`WARNING: Non-consecutive header level increase; 1 to 3 [myst.header]`
#2611 
Here I have modified the level 3 headings to be level 2 headings
> fix non-consecutive headings

- book/website/communication/citable/citable-orcid.md
Currently, building the book prompts this pair of errors:
- WARNING: duplicate label orcid-ids, other instance in C:\Users\cege-user\Documents\the-turing-way_main\book\website\communication\citable\citable-orcid.md←[39;49;00m
- WARNING: duplicate label orcid-ids, other instance in C:\Users\cege-user\Documents\the-turing-way_main\book\website\communication\citable.md←[39;49;00m
To resolve this, I have renamed one of the figure reference names. 
Not listed in the original errors of #2611, since it has been introduced since, but it seems worth linking it back to that.
> modify one of the orcid figure names to avoid a reference clash

- .github/workflows/ci.yml
- .github/workflows/contributors-record.yml
- .github/workflows/lorem-ipsums.yml
- .github/workflows/no-bad-latin.yml
- .github/workflows/release-workflow.yml
- .github/workflows/test-file-size.yml
- .github/workflows/yamllint.yaml
- book/website/reproducible-research/ci/ci-building-gh-actions.md
This should take care of many of the warnings we see in the Actions tab. Also, it's never a bad idea to stay away from EOL python.
> CI: update versions

- ways_of_working.md
Partially addresses #2851 
In order to codify infrastructure maintenance and ongoing roles within the project, this Ways of Working document is being updated to add @sgibson91, @da5nsy, @JimMadge, @bsipocz as infrastructure maintenance co-leads. 
This format mimicks the title & system used by the Localisation and Translation team (which has self-identified within their team as co-leads). Is this something that this group of people would like to use as well? Is there another format or title that you would like to use?
> Adding infrastructure maintainers to Ways of Working

- book/website/collaboration/research-infrastructure-roles/data-wrangler.md
Fixes #2897
I'm not sure if this is documented in jupyter-book, or a bug, but it looks like the reason that the title override wasn't being respected was that there were two level 1 headers in that file.
> Remove extra h1 to fix #2897

- book/website/community-handbook/coworking/coworking-collabcafe.md
The referenced issue to developing a hosting guide for collab cafe is now closed (#925 ), so reword the reference to it on the website to avoid confusion.
> Remove mention of developing a hosting guide from collab cafe page

- LICENSE.md
- book/website/LICENSE.md
- book/website/_config.yml
- Update the website footer to remove copyright assertion, and replace it with a link to the project licenses.
- Minor tweaks updating links as I went
Resolves #2772 
Followed these instructions: https://jupyterbook.org/en/stable/advanced/html.html?#adding-a-license-to-your-html-footer
> Update the website footer to remove copyright assertion, and replace it with a link to the project licenses

- book/website/reproducible-research/code-quality/code-quality-style.md
Fixes a dead link to the eScience Center language guides.
* Old (dead) link: https://guide.esciencecenter.nl/best_practices/language_guides/languages_overview.html
* New (working) link: https://guide.esciencecenter.nl/#/best_practices/language_guides/languages_overview
* Dead link fix
* Check if the new link points to the right page
> Fixed dead link to eScience Center language guides

- .github/ISSUE_TEMPLATE/Request-Translation
This is a template for the translation made in [Crowdin](https://turingway.crowdin.com/turing-way), related to #2365. It's based largely on the already existed templates with minor changes.
* *Adding new issue template for the translation so others can request translation through GH*
> Add template for the translation

- book/website/community-handbook/style/style-citing.md
There is a mismatch between the example given, and the reference actually used.
> Update example reference

- book/website/community-handbook/newsletters/newsletters-process.md
* Based on a prompt from Alex, I realised that the Zenodo community page is not linked to the process document where talks from events are uploaded/centralised
* A few recently added sections in the newsletter were also missing
* Minor addition to update the newsletter process doc
> Update newsletters-process with Zenodo link and missing sections

- CONTRIBUTING.md
While reading the contribution guidelines in `CONTRIBUTING.md`, I noticed a broken link.
* Fix link to "Continuous Integration chapter"
_Whether anything needs to get done here depends on if #3174 (my first contribution) is merged before this._
https://github.com/spier
> Fix link to Continuous Integration chapter

- book/website/community-handbook/style.md
This commit improves the Style guidelines about Latin abbreviations.
The image caption is updated to clarify that a screenshot is used to avoid triggering CI failures (at the point where the image is first encountered, instead of later in the text).
Also, the hyperlink to the Gov.UK style guide is updated to point to the specific section on Latin abbreviations instead of the style guide as a whole.
> Latin abbrevs: better image caption and link

- book/website/communication/binder/zero-to-binder.md
numpy v1.14.* no longer works on mybinder.org when using the Python version set by default. This is because the Python version has been upgraded beyond what will support this old version of numpy. So, we recommend a newer version of numpy to install instead which is compatible with the Python default in mybinder.org.
> Suggest a more recent version of numpy to install in z2b tutorial

- README.md
The link to the Chinese readme appears to have been accidentally excluded until now.
> Add link to Chinese readme

- book/website/afterword/contributors-record.md
- book/website/community-handbook/infrastructure/infrastructure-contributors.md
- contributors.md
> Fix link on Record of Contributions, and also add a header note signalling towards the infrastructure documentation for that page

- book/website/reproducible-research/vcs/vcs-resources.md
Github learning lab link is broken
> If you've used Learning Lab, we recommend trying a GitHub Skills course for the latest content and an updated learning experience backed by GitHub Actions
From: https://github.blog/changelog/2022-09-01-deprecating-learning-lab/
> Change Learning Lab Github link

- book/website/collaboration/research-infrastructure-roles/data-wrangler.md
Fixes #3286 
Adding a new employer to the Data Wrangler page in the Research Infrastructure Section 
- Added suggested text by @AdamHollings in #3286
> Add NHS England as employer for /collaboration/research-infrastructure-roles/data-wrangler.html

- book/website/reproducible-research/testing.md
- book/website/reproducible-research/testing/testing-exceptions.md
Fixes #3238 by adding alternative text descriptions for images in _Guide for Reproducible Research_ -> _Code Testing_
- alt-text descriptions in this file based on guidance provided in https://nightingaledvs.com/writing-alt-text-for-data-visualization/
> add alternative text descriptions for images in Testing

- .github/config.yml
The WelcomeBot used in this repo is using 3 different images to thank new contributors.
I noticed that the images were not working any more, as evident in [this example](https://github.com/the-turing-way/the-turing-way/pull/3288#issuecomment-1716796853):
I don't know why the old image URLs stopped working.
It might have to do with API changes that were zenodo launched on Oct 13th but that is just a hunch:
https://help.zenodo.org/docs/about/whats-changed/
https://blog.zenodo.org/2022/12/07/2022-12-07-zenodo-on-inveniordm/
zenodo says that their changes should not contain any breaking changes but who knows, maybe this was an unintended side-effect?
_As an aside:_ I tried to find a zenodo Support channel where I can report this issue but could not find an appropriate one sof ar.
* adding new …
> Replace broken images used by the Welcome Bot

- book/website/communication/citable/citable-resources.md
The website doesn't refer to the specified page anymore https://guide.esciencecenter.nl/#/best_practices/documentation?id=software-citation
Fixes #NA
* Just the one link
> Alternative for broken link

- CONTRIBUTING.md
I have changed the erroneous link to a new chapter suggestion issue template in `CONTRIBUTING.md`: Fixes #3362.
* Change https://github.com/the-turing-way/the-turing-way/issues/new?assignees=&template=CHAPTER_ISSUE_TEMPLATE.md to https://github.com/the-turing-way/the-turing-way/issues/new?assignees=&labels=book&projects=&template=new_chapter.yml&title=%5BNEW+CHAPTER%5D+-+%3CTOPIC%3E
> [Ready to merge] Changing chapter suggestion issue link in CONTRIBUTING.md

- .all-contributorsrc
Adding content contribution-type for Susana Roman Garcia, because the bot won't add it "again" (except it's not there)
> [ready for review] Manually update .all-contributorsrc

- book/website/community-handbook/style/style-crossref.md
Rationalises the examples of cross referencing in the `community-handbook/style/style-crossref section`.
Since the relative locations of the reference and citation don't affect the syntax, the three examples have been combined into a single example to help simplify the text.
Fixes #3349.
I also considered @kallewesterling's nice suggestion to add an example that includes a label, but noticed that it looks like this case is already covered in the section on the page ["Providing an alternative title for the references"](https://the-turing-way.netlify.app/community-handbook/style/style-crossref#providing-an-alternative-title-for-the-references), so I think there's no need to add this example. However another possibility might be to combine the section below into the examples.
* Combines the …
> Rationalise cross referencing examples

- .github/config.yml
This fixes issue #3413 
* Changed ToC link in https://github.com/the-turing-way/the-turing-way/blob/main/.github/config.yml (under newPRWelcomeComment) to https://github.com/the-turing-way/the-turing-way/blob/main/book/website/_toc.yml
> [Ready for review] Corrected ToC link on config.yml

- book/README.md
- book/website/community-handbook/local-build.md
There was a problem discussed in #3368 where there were different instructions for how to deploy the book locally. These revision addresses that problem by:
Resolves #3368.
> [Ready for review] Adjusting instructions for local builds in two different files

- governance/community-calls/20240304-coworking.md
- governance/community-calls/20240311-coworking.md
- governance/community-calls/20240318-coworking.md
- governance/community-calls/20240325-coworking.md
Archiving coworking call notes for:
- 26 February
- 4 March
- 11 March
- 18 March
- 25 March
> [Ready for review] Add coworking notes from march 2024

- project_management/quarterly_reports/book-stats.md
- project_management/quarterly_reports/count-chapters.sh
* Adding a shell script for reporting
* Shell script and latest stats for chapters and subchapters added to the quarterly report
> Share script for book stats for reporting

- book/website/reproducible-research/licensing.md
The Licensing section made a point of distinguishing between American and British English, but for British English, both noun and verb were still spelled as `license`.
- Replace `license` with `licence` when referring to the noun in British English
> actually distinguish between licence and license

- book/website/index.md
- book/website/reproducible-research/open/open-source.md
Alternative proposal for #3705 if the concept of « open source » is assumed strictly related to software.
Context for origin of the proposal: https://github.com/the-turing-way/the-turing-way/pull/3705#issuecomment-2161237778
Problematic situation where « open source » is explained and usually assumed in relation to software, but used to qualify the Turing Way handbook in an unclear manner as it is a non-software artefact. This fuels confusion about the concept.
This is coming next to debates on the meaning of open source beyond software, which may be applied to digital resources whose sources are provided. Questioning regarding the fact open source should be used only for software, PR for this case.
Need of an appropriate use of the terminology through the resource and provide explanation …
> Homepage: avoid qualifying The Turing Way as open source

- book/website/_bibliography/references.bib
- book/website/reproducible-research/open/open-source.md
Add 2 references mentioned in the text but not present in the bibliography to the bibliography, and add a cross reference to open source licensing chapter where it was mentioned here.
Addresses some points raised in #3705 
* cross reference licensing chapter on first mention of 'open-source licence'
* Add reference to Gorgolewski et al 2016 to the bibliography
* Add reference to Pedregosa et al. 2012 to the bibliography
> Add references to the bibliography and a cross reference in open source software

- book/website/collaboration/maintain-review.md
Adding governance-maintainers image to the collaboration sub-chapter.
> Adding governance-maintainers image

- book/website/foreword/cite.md
One of the links to the Zenodo repository for the book incorrectly had the repository for the illustrations as its target (despite the link text being the correct DOI).
* Fix one mistargeted link in cite.md
> Fix incorrect link in cite.md

- book/website/_config.yml
It's been ~7 months since we switched domains and added a banner.
I think it has served its purpose and it might be time (now or soon) to remove it.
This PR removes the banner which was introduced here: https://github.com/the-turing-way/the-turing-way/pull/3537
> Remove banner

- book/website/foreword/cite.md
adding correct alt text for thanks banner image
Fixes #<NUM>
adding alt text
> Update cite image.md

- book/website/reproducible-research/rdm/rdm-metadata.md
- book/website/reproducible-research/rdm/rdm-storage.md
Fixed the typos in two figure's alt text. 
Addresses (but does not close) #3882
* Alt text for documentation figure
* Alt text for data structure for research data figure
> fix typos in alt text

- CONTRIBUTING.md
- book/website/_toc.yml
- book/website/community-handbook/accessibility.md
- book/website/community-handbook/accessibility/accessibility-policy.md
- book/website/community-handbook/contributing-guideline.md
Congrats Liz and Anne for merging the Accessibility Policy draft in the GitHub
With this PR I am creating a linked document to display the contributing guideline and accessibility policy documents in the book (without making a duplicate draft)
* Add accessibility policy doc
* Add contributing policy doc
> Add policy docs in the community handbook

- netlify.toml
index.html no longer exists so old redirects will encounter an error. All of these (and index.html) not point to the website root.
Closes #4054 
* Add redirect from `/index.html` to `/`
* Modify old home page redirects to point to `/` rather than `/index.html`
@jezcope for bug and infra
> Update redirect rules for jb2

- book/website/myst.yml
This should add little buttons to each page that link to the licences we use.
Taken from [here](https://github.com/jupyter-book/mystmd/blob/0ca2c6792b3f83d58942788cf499d495a9e3e73d/docs/myst.yml#L5-L7).
> Add licences to myst.yml

- book/website/project-design/pd-overview.md
- book/website/project-design/pd-overview/pd-overview-repro.md
Fixes some block-quote styling by using the construct
```markdown
> Text
> 
> -- An attribution
```
Old:
New:
- Block-quote attribution formatting
> fix: use \n\n-- for blockquote attribution

- CONTRIBUTING.md
We currently have local build instructions in 2 separate places. This PR removes one and replaces it with a link to the other.
> align local build instructions

- .github/ISSUE_TEMPLATE/05_general.yml
The last box on this github form had `render: markdown` which meant that you couldn't actually `@` folks to help!
* Removes `render: markdown` from a github form template
> Don't render part of the "General" github form as markdown

- netlify.toml
This PR updates the Turing Way’s site configuration to allow **Cross-Origin Resource Sharing (CORS)** from all origins (`Access-Control-Allow-Origin: *`). This change is being made to:
* Support **MyST cross-references** (e.g., `xref` links, [see docs](https://mystmd.org/guide/external-references#myst-xref)) **from other sites** that use The Turing Way as a citation source.
* Enable content embedding, linking, or automated metadata access (e.g., for previews or API consumers) **without authentication or same-origin constraints**.
**CORS** is a browser security feature that restricts how resources on a web page can be requested from another domain outside the one that served the web page. For example, JavaScript running on `external-site.org` cannot fetch metadata or assets from …
> Enable Cross-Reference in MyST via CORS

- tests/lorem-ipsums.py
- related to #4104
The filenames are strings, not path objects, so don't have such a method
> Remove .name method call when appending filenames to a list

- netlify.toml
#4045 introduced some problems.
Redirects which were intended to correct the location of the top pages for chapters were made into wildcards. So, for example,
`https://book.the-turing-way.org/reproducible-research/ --> https://book.the-turing-way.org/reproducible-research/reproducible-research` correct
`https://book.the-turing-way.org/reproducible-research/overview --> https://book.the-turing-way.org/reproducible-research/reproducible-research/overview` incorrect
This PR removes those wildcards, but leaves wildcards in place where entire chapters have moved name, for example, `/version_control` to `/reproducible-research/vcs`.
> Correct redirects

- .github/workflows/ci.yml
- .github/workflows/lorem-ipsums.yml
- .github/workflows/no-bad-latin.yml
@the-turing-way/infrastructure-working-group recently turned on branch protection rules for `main`, meaning that certain checks would need to pass before merging was allowed.
This had the unintended consequence of blocking certain PRs from being merged (by anyone other than a user with admin permissions who could bypass the branch protection rules). This affected PRs which **only** modified files which were outside of the CI path spec:
https://github.com/the-turing-way/the-turing-way/blob/226f9b2ace7c8dcaccf104999e0cda9eaf836b63/.github/workflows/ci.yml#L11-L16
For example: 
- all-contributors-bot PRs, e.g. https://github.com/the-turing-way/the-turing-way/pull/4276
- things which just change netlify deploy info: https://github.com/the-turing-way/the-turing-way/pull/4156
- others (?)
This …
> remove CI path filtering

- .github/workflows/ci.yml
This PR **does not** change the current behaviour of the CI workflow, but instead makes the syntax more understandable by humans.
* Removes a job-level `if` condition that prevented the workflow running on pushes to `main` and any PRs opened by the all-contributors bot
* Reimplements the same logic as above but in the `on:` keyword, improving readability for maintainers
> Simplify conditions for CI workflow

- book/website/reproducible-research/overview/overview-resources.md
@stefanv was looking at The Turing Way website, and noticed that a particular file heading doesn't behave properly:
After a little bit of digging, I found a BOM at the head of the file, which is invisible to the human eye but not to the tokeniser:
```
$ cat -v /book/website/reproducible-research/overview/overview-resources.md| head
M-oM-;M-?# Resources
For additional resources like videos and reference papers on reproducibility, see the {ref}`rr-overview-resources-reading` and {ref}`rr-overview-resources-addmaterial` sections.
(rr-overview-resources-learn)=
```
This PR strips that mark. I searched for other files, and this is the only one affected.
> [!Note]
> Should we introduce a Git hook (pre-commit) to catch this? e.g. https://gist.github.com/rlee287/e6026243dedc38398298
> fix: remove BOM in file

- book/website/references.bib
icon and ==== are breaking embedding reference.bib in different repositories.
> Update malformed references.bib

- .github/workflows/crowdin-contributors.yml
This reverts commit ff21cd7f46328b4d5c068083d2ddd50b8d21909a.
Forgot to do this in #4323
> Correct secret name in crowdin workflow

- book/website/community-handbook/style/consistency/consistency-language.md
- book/website/community-handbook/style/style-writing-markdown.md
I quickly needed a reference elsewhere for why we should avoid latin abbreviations. Unfortunately the TTW references were at 3 different places and not cleanly linking to each other.
And it was mentioning CI as some kind of magic rather than just a tool that enforces the style rule we came up with.
So this PR: makes the references more accurarate, and rephrase/cleanup CI mentions.
> MAINT: cleanup latin style guide pointers
